import { Movie, Profile } from "@/types";

export const DEFAULT_PROFILES: Profile[] = [
  {
    id: "profile_1",
    name: "VIP Member",
    avatar: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=200&h=200&q=80",
    pinCode: "", // No PIN by default, can be set
    isKids: false,
  },
  {
    id: "profile_2",
    name: "Family / Kids",
    avatar: "https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?auto=format&fit=crop&w=200&h=200&q=80",
    pinCode: "1234", // Sample PIN locked profile
    isKids: true,
  },
];

export const INITIAL_MOVIES: Movie[] = [
  {
    id: "m_dune2",
    imdbId: "tt15239678",
    title: "Dune: Part Two",
    originalTitle: "Dune: Part Two",
    description: "Paul Atreides unites with Chani and the Fremen while seeking revenge against the conspirators who destroyed his family. Facing a choice between the love of his life and the fate of the universe, he endeavors to prevent a terrible future.",
    backdropUrl: "https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=1920&q=80",
    posterUrl: "https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=600&q=80",
    trailerYoutubeId: "Way9Dexny3w",
    videoUrl: "/sample.mp4",
    duration: "2h 46m",
    durationSeconds: 9960,
    releaseYear: 2024,
    matchPercentage: 99,
    ageRating: "16+",
    quality: "4K UHD",
    genres: ["Sci-Fi", "Adventure", "Action"],
    cast: ["Timothée Chalamet", "Zendaya", "Rebecca Ferguson", "Javier Bardem"],
    director: "Denis Villeneuve",
    isTrending: true,
    isTop10: true,
    top10Rank: 1,
    isFilmFlexOriginal: true,
    subtitles: [
      { id: "sub_ar", label: "العربية (Arabic)", language: "ar", src: "/subtitles/sample_ar.vtt", isDefault: true },
      { id: "sub_fr", label: "Français (French)", language: "fr", src: "/subtitles/sample_fr.vtt" },
      { id: "sub_en", label: "English [CC]", language: "en", src: "/subtitles/sample_en.vtt" },
    ],
    audioTracks: [
      { id: "aud_en", label: "English - Dolby Atmos 5.1", language: "en", isDefault: true },
      { id: "aud_fr", label: "Français - Doublage", language: "fr" },
    ],
  },
  {
    id: "m_oppenheimer",
    imdbId: "tt15398776",
    title: "Oppenheimer",
    originalTitle: "Oppenheimer",
    description: "The story of American scientist J. Robert Oppenheimer and his role in the development of the atomic bomb during World War II, exploring the moral paradoxes and political fallout.",
    backdropUrl: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=1920&q=80",
    posterUrl: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=600&q=80",
    trailerYoutubeId: "uYPbbksJxIg",
    videoUrl: "/sample.mp4",
    duration: "3h 00m",
    durationSeconds: 10800,
    releaseYear: 2023,
    matchPercentage: 98,
    ageRating: "18+",
    quality: "4K UHD",
    genres: ["Biography", "Drama", "History"],
    cast: ["Cillian Murphy", "Emily Blunt", "Matt Damon", "Robert Downey Jr."],
    director: "Christopher Nolan",
    isTrending: true,
    isTop10: true,
    top10Rank: 2,
    subtitles: [
      { id: "sub_ar", label: "العربية (Arabic)", language: "ar", src: "/subtitles/sample_ar.vtt", isDefault: true },
      { id: "sub_fr", label: "Français (French)", language: "fr", src: "/subtitles/sample_fr.vtt" },
      { id: "sub_en", label: "English [CC]", language: "en", src: "/subtitles/sample_en.vtt" },
    ],
    audioTracks: [
      { id: "aud_en", label: "English - Original 5.1", language: "en", isDefault: true },
      { id: "aud_fr", label: "Français - VFF", language: "fr" },
    ],
  },
  {
    id: "m_spiderverse",
    imdbId: "tt9362722",
    title: "Spider-Man: Across the Spider-Verse",
    originalTitle: "Spider-Man: Across the Spider-Verse",
    description: "Miles Morales catapults across the Multiverse, where he encounters a team of Spider-People charged with protecting its very existence. When heroes clash, Miles must redefine what it means to be a hero.",
    backdropUrl: "https://images.unsplash.com/photo-1635805737707-575885ab0820?auto=format&fit=crop&w=1920&q=80",
    posterUrl: "https://images.unsplash.com/photo-1635805737707-575885ab0820?auto=format&fit=crop&w=600&q=80",
    trailerYoutubeId: "cqGjhVJWtEg",
    videoUrl: "/sample.mp4",
    duration: "2h 20m",
    durationSeconds: 8400,
    releaseYear: 2023,
    matchPercentage: 97,
    ageRating: "13+",
    quality: "4K UHD",
    genres: ["Animation", "Action", "Adventure"],
    cast: ["Shameik Moore", "Hailee Steinfeld", "Oscar Isaac"],
    director: "Joaquim Dos Santos, Kemp Powers",
    isTrending: true,
    isTop10: true,
    top10Rank: 3,
    subtitles: [
      { id: "sub_ar", label: "العربية (Arabic)", language: "ar", src: "/subtitles/sample_ar.vtt", isDefault: true },
      { id: "sub_fr", label: "Français (French)", language: "fr", src: "/subtitles/sample_fr.vtt" },
      { id: "sub_en", label: "English [CC]", language: "en", src: "/subtitles/sample_en.vtt" },
    ],
    audioTracks: [
      { id: "aud_en", label: "English - Original", language: "en", isDefault: true },
      { id: "aud_fr", label: "Français", language: "fr" },
    ],
  },
  {
    id: "m_inception",
    imdbId: "tt1375666",
    title: "Inception",
    originalTitle: "Inception",
    description: "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O., but his tragic past may doom the project.",
    backdropUrl: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=1920&q=80",
    posterUrl: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=600&q=80",
    trailerYoutubeId: "YoHD9XEInc0",
    videoUrl: "/sample.mp4",
    duration: "2h 28m",
    durationSeconds: 8880,
    releaseYear: 2010,
    matchPercentage: 99,
    ageRating: "13+",
    quality: "4K UHD",
    genres: ["Action", "Sci-Fi", "Thriller"],
    cast: ["Leonardo DiCaprio", "Joseph Gordon-Levitt", "Elliot Page"],
    director: "Christopher Nolan",
    isTop10: true,
    top10Rank: 4,
    subtitles: [
      { id: "sub_ar", label: "العربية (Arabic)", language: "ar", src: "/subtitles/sample_ar.vtt", isDefault: true },
      { id: "sub_fr", label: "Français", language: "fr", src: "/subtitles/sample_fr.vtt" },
      { id: "sub_en", label: "English [CC]", language: "en", src: "/subtitles/sample_en.vtt" },
    ],
    audioTracks: [
      { id: "aud_en", label: "English [Original]", language: "en", isDefault: true },
      { id: "aud_fr", label: "Français", language: "fr" },
    ],
  },
  {
    id: "m_dark_knight",
    imdbId: "tt0468569",
    title: "The Dark Knight",
    originalTitle: "The Dark Knight",
    description: "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.",
    backdropUrl: "https://images.unsplash.com/photo-1509248961158-e54f6934749c?auto=format&fit=crop&w=1920&q=80",
    posterUrl: "https://images.unsplash.com/photo-1509248961158-e54f6934749c?auto=format&fit=crop&w=600&q=80",
    trailerYoutubeId: "EXeTwQWrcwY",
    videoUrl: "/sample.mp4",
    duration: "2h 32m",
    durationSeconds: 9120,
    releaseYear: 2008,
    matchPercentage: 99,
    ageRating: "16+",
    quality: "4K UHD",
    genres: ["Action", "Crime", "Drama"],
    cast: ["Christian Bale", "Heath Ledger", "Aaron Eckhart"],
    director: "Christopher Nolan",
    isTop10: true,
    top10Rank: 5,
    subtitles: [
      { id: "sub_ar", label: "العربية (Arabic)", language: "ar", src: "/subtitles/sample_ar.vtt", isDefault: true },
      { id: "sub_fr", label: "Français", language: "fr", src: "/subtitles/sample_fr.vtt" },
    ],
    audioTracks: [
      { id: "aud_en", label: "English [Original]", language: "en", isDefault: true },
      { id: "aud_fr", label: "Français", language: "fr" },
    ],
  },
  {
    id: "m_interstellar",
    imdbId: "tt0816692",
    title: "Interstellar",
    originalTitle: "Interstellar",
    description: "When Earth becomes uninhabitable in the future, a farmer and ex-NASA pilot, Joseph Cooper, is tasked to pilot a spacecraft, along with a team of researchers, to find a new planet for humans.",
    backdropUrl: "https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?auto=format&fit=crop&w=1920&q=80",
    posterUrl: "https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?auto=format&fit=crop&w=600&q=80",
    trailerYoutubeId: "zSWdZVtXT7E",
    videoUrl: "/sample.mp4",
    duration: "2h 49m",
    durationSeconds: 10140,
    releaseYear: 2014,
    matchPercentage: 98,
    ageRating: "13+",
    quality: "4K UHD",
    genres: ["Sci-Fi", "Adventure", "Drama"],
    cast: ["Matthew McConaughey", "Anne Hathaway", "Jessica Chastain"],
    director: "Christopher Nolan",
    isTop10: true,
    top10Rank: 6,
    subtitles: [
      { id: "sub_ar", label: "العربية (Arabic)", language: "ar", src: "/subtitles/sample_ar.vtt", isDefault: true },
      { id: "sub_fr", label: "Français", language: "fr", src: "/subtitles/sample_fr.vtt" },
    ],
    audioTracks: [
      { id: "aud_en", label: "English - DTS", language: "en", isDefault: true },
    ],
  },
  {
    id: "m_stranger_things",
    imdbId: "tt4574334",
    title: "Stranger Things",
    originalTitle: "Stranger Things",
    description: "When a young boy vanishes, a small town uncovers a mystery involving secret experiments, terrifying supernatural forces and one strange little girl.",
    backdropUrl: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=1920&q=80",
    posterUrl: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=600&q=80",
    trailerYoutubeId: "b9EkMc79ZSU",
    videoUrl: "/sample.mp4",
    duration: "4 Seasons",
    durationSeconds: 3600,
    releaseYear: 2022,
    matchPercentage: 96,
    ageRating: "16+",
    quality: "HDR",
    genres: ["Sci-Fi", "Horror", "Drama"],
    cast: ["Millie Bobby Brown", "Finn Wolfhard", "Winona Ryder"],
    isFilmFlexOriginal: true,
    isTrending: true,
    isTop10: true,
    top10Rank: 7,
    subtitles: [
      { id: "sub_ar", label: "العربية (Arabic)", language: "ar", src: "/subtitles/sample_ar.vtt", isDefault: true },
      { id: "sub_fr", label: "Français", language: "fr", src: "/subtitles/sample_fr.vtt" },
    ],
    audioTracks: [{ id: "aud_en", label: "English", language: "en", isDefault: true }],
  },
  {
    id: "m_cyberpunk",
    imdbId: "tt12590266",
    title: "Cyberpunk: Edgerunners",
    originalTitle: "Cyberpunk: Edgerunners",
    description: "A street kid trying to survive in a technology and body modification-obsessed city of the future. Having everything to lose, he chooses to stay alive by becoming an edgerunner.",
    backdropUrl: "https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&w=1920&q=80",
    posterUrl: "https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&w=600&q=80",
    trailerYoutubeId: "JtqIas3bYhg",
    videoUrl: "/sample.mp4",
    duration: "10 Episodes",
    durationSeconds: 1500,
    releaseYear: 2022,
    matchPercentage: 97,
    ageRating: "18+",
    quality: "4K UHD",
    genres: ["Animation", "Action", "Sci-Fi"],
    cast: ["KENN", "Aoi Yuuki", "Hiroki Touchi"],
    isTrending: true,
    isTop10: true,
    top10Rank: 8,
    subtitles: [
      { id: "sub_ar", label: "العربية (Arabic)", language: "ar", src: "/subtitles/sample_ar.vtt", isDefault: true },
      { id: "sub_fr", label: "Français", language: "fr", src: "/subtitles/sample_fr.vtt" },
    ],
    audioTracks: [
      { id: "aud_ja", label: "Japanese [Original]", language: "ja", isDefault: true },
      { id: "aud_en", label: "English", language: "en" },
    ],
  },
  {
    id: "m_john_wick_4",
    imdbId: "tt10366206",
    title: "John Wick: Chapter 4",
    originalTitle: "John Wick: Chapter 4",
    description: "John Wick uncovers a path to defeating The High Table. But before he can earn his freedom, Wick must face off against a new enemy with powerful alliances across the globe.",
    backdropUrl: "https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?auto=format&fit=crop&w=1920&q=80",
    posterUrl: "https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?auto=format&fit=crop&w=600&q=80",
    trailerYoutubeId: "qEVUtrk8_B4",
    videoUrl: "/sample.mp4",
    duration: "2h 49m",
    durationSeconds: 10140,
    releaseYear: 2023,
    matchPercentage: 95,
    ageRating: "18+",
    quality: "4K UHD",
    genres: ["Action", "Crime", "Thriller"],
    cast: ["Keanu Reeves", "Donnie Yen", "Bill Skarsgård"],
    director: "Chad Stahelski",
    isTop10: true,
    top10Rank: 9,
    subtitles: [
      { id: "sub_ar", label: "العربية (Arabic)", language: "ar", src: "/subtitles/sample_ar.vtt", isDefault: true },
      { id: "sub_fr", label: "Français", language: "fr", src: "/subtitles/sample_fr.vtt" },
    ],
    audioTracks: [{ id: "aud_en", label: "English", language: "en", isDefault: true }],
  },
  {
    id: "m_gladiator_2",
    imdbId: "tt9660502",
    title: "Gladiator II",
    originalTitle: "Gladiator II",
    description: "Years after witnessing the death of the revered hero Maximus at the hands of his uncle, Lucius must enter the Colosseum after his home is conquered by the tyrannical Emperors who now lead Rome.",
    backdropUrl: "https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?auto=format&fit=crop&w=1920&q=80",
    posterUrl: "https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?auto=format&fit=crop&w=600&q=80",
    trailerYoutubeId: "4rgYUipGJNo",
    videoUrl: "/sample.mp4",
    duration: "2h 28m",
    durationSeconds: 8880,
    releaseYear: 2024,
    matchPercentage: 94,
    ageRating: "16+",
    quality: "4K UHD",
    genres: ["Action", "Adventure", "Drama"],
    cast: ["Paul Mescal", "Pedro Pascal", "Denzel Washington"],
    director: "Ridley Scott",
    isTop10: true,
    top10Rank: 10,
    subtitles: [
      { id: "sub_ar", label: "العربية (Arabic)", language: "ar", src: "/subtitles/sample_ar.vtt", isDefault: true },
      { id: "sub_fr", label: "Français", language: "fr", src: "/subtitles/sample_fr.vtt" },
    ],
    audioTracks: [{ id: "aud_en", label: "English", language: "en", isDefault: true }],
  },
  {
    id: "m_deadpool_wolverine",
    imdbId: "tt6263850",
    title: "Deadpool & Wolverine",
    originalTitle: "Deadpool & Wolverine",
    description: "Wolverine is recovering from his injuries when he crosses paths with the loudmouth Deadpool. They team up to defeat a common enemy in a multiverse-spanning adventure.",
    backdropUrl: "https://images.metahub.space/background/medium/tt6263850/img",
    posterUrl: "https://images.metahub.space/poster/small/tt6263850/img",
    trailerYoutubeId: "73_1biulkYk",
    videoUrl: "/sample.mp4",
    duration: "2h 08m",
    durationSeconds: 7680,
    releaseYear: 2024,
    matchPercentage: 98,
    ageRating: "16+",
    quality: "4K UHD",
    genres: ["Action", "Comedy", "Sci-Fi"],
    cast: ["Ryan Reynolds", "Hugh Jackman", "Emma Corrin"],
    director: "Shawn Levy",
    isTrending: true,
    subtitles: [{ id: "sub_ar", label: "العربية", language: "ar", isDefault: true }],
    audioTracks: [{ id: "aud_en", label: "English", language: "en", isDefault: true }],
  },
  {
    id: "m_joker2",
    imdbId: "tt11315808",
    title: "Joker: Folie à Deux",
    originalTitle: "Joker: Folie à Deux",
    description: "Arthur Fleck est interné à l'asile d'Arkham en attendant son procès. Alors qu'il lutte avec sa double identité, Arthur rencontre le grand amour et trouve la musique qui a toujours sommeillé en lui.",
    backdropUrl: "https://images.metahub.space/background/medium/tt11315808/img",
    posterUrl: "https://images.metahub.space/poster/small/tt11315808/img",
    trailerYoutubeId: "BD6Uf4qHEmk",
    videoUrl: "/sample.mp4",
    duration: "2h 18m",
    durationSeconds: 8280,
    releaseYear: 2024,
    matchPercentage: 93,
    ageRating: "16+",
    quality: "4K UHD",
    genres: ["Crime", "Drama", "Musical"],
    cast: ["Joaquin Phoenix", "Lady Gaga", "Brendan Gleeson"],
    director: "Todd Phillips",
    isTrending: true,
    subtitles: [{ id: "sub_ar", label: "العربية", language: "ar", isDefault: true }],
    audioTracks: [{ id: "aud_en", label: "English", language: "en", isDefault: true }],
  },
  {
    id: "m_avatar2",
    imdbId: "tt1630029",
    title: "Avatar: The Way of Water",
    originalTitle: "Avatar: The Way of Water",
    description: "Jake Sully vit avec sa nouvelle famille formée sur la planète Pandora. Lorsqu'une menace familière revient pour achever ce qui avait été commencé, Jake doit faire équipe avec Neytiri et l'armée des Na'vi.",
    backdropUrl: "https://images.metahub.space/background/medium/tt1630029/img",
    posterUrl: "https://images.metahub.space/poster/small/tt1630029/img",
    trailerYoutubeId: "d9MyW72ELq0",
    videoUrl: "/sample.mp4",
    duration: "3h 12m",
    durationSeconds: 11520,
    releaseYear: 2022,
    matchPercentage: 97,
    ageRating: "13+",
    quality: "4K UHD",
    genres: ["Action", "Adventure", "Sci-Fi"],
    cast: ["Sam Worthington", "Zoe Saldana", "Sigourney Weaver"],
    director: "James Cameron",
    isTrending: true,
    subtitles: [{ id: "sub_ar", label: "العربية", language: "ar", isDefault: true }],
    audioTracks: [{ id: "aud_en", label: "English", language: "en", isDefault: true }],
  },
  {
    id: "m_the_batman",
    imdbId: "tt1877830",
    title: "The Batman",
    originalTitle: "The Batman",
    description: "When a sadistic serial killer begins murdering key political figures in Gotham, Batman is forced to investigate the city's hidden corruption and question his family's involvement.",
    backdropUrl: "https://images.metahub.space/background/medium/tt1877830/img",
    posterUrl: "https://images.metahub.space/poster/small/tt1877830/img",
    trailerYoutubeId: "mqqft2x_Aa4",
    videoUrl: "/sample.mp4",
    duration: "2h 56m",
    durationSeconds: 10560,
    releaseYear: 2022,
    matchPercentage: 96,
    ageRating: "16+",
    quality: "4K UHD",
    genres: ["Action", "Crime", "Drama", "Thriller"],
    cast: ["Robert Pattinson", "Zoë Kravitz", "Paul Dano", "Colin Farrell"],
    director: "Matt Reeves",
    subtitles: [{ id: "sub_ar", label: "العربية", language: "ar", isDefault: true }],
    audioTracks: [{ id: "aud_en", label: "English", language: "en", isDefault: true }],
  },
  {
    id: "m_top_gun_maverick",
    imdbId: "tt1745960",
    title: "Top Gun: Maverick",
    originalTitle: "Top Gun: Maverick",
    description: "After thirty years, Maverick is still pushing the envelope as a top naval aviator, but must confront ghosts of his past when he leads TOP GUN's elite graduates on an impossible mission.",
    backdropUrl: "https://images.metahub.space/background/medium/tt1745960/img",
    posterUrl: "https://images.metahub.space/poster/small/tt1745960/img",
    trailerYoutubeId: "giXco2JAZ_4",
    videoUrl: "/sample.mp4",
    duration: "2h 10m",
    durationSeconds: 7800,
    releaseYear: 2022,
    matchPercentage: 97,
    ageRating: "13+",
    quality: "4K UHD",
    genres: ["Action", "Drama"],
    cast: ["Tom Cruise", "Miles Teller", "Jennifer Connelly"],
    director: "Joseph Kosinski",
    subtitles: [{ id: "sub_ar", label: "العربية", language: "ar", isDefault: true }],
    audioTracks: [{ id: "aud_en", label: "English", language: "en", isDefault: true }],
  },
  {
    id: "m_fight_club",
    imdbId: "tt0137523",
    title: "Fight Club",
    originalTitle: "Fight Club",
    description: "An insomniac office worker looking for a way to change his life crosses paths with a devil-may-care soap maker and they form an underground fight club that evolves into something much more.",
    backdropUrl: "https://images.metahub.space/background/medium/tt0137523/img",
    posterUrl: "https://images.metahub.space/poster/small/tt0137523/img",
    trailerYoutubeId: "qtRKDV93gk8",
    videoUrl: "/sample.mp4",
    duration: "2h 19m",
    durationSeconds: 8340,
    releaseYear: 1999,
    matchPercentage: 98,
    ageRating: "18+",
    quality: "4K UHD",
    genres: ["Drama", "Thriller", "Mystery"],
    cast: ["Brad Pitt", "Edward Norton", "Helena Bonham Carter"],
    director: "David Fincher",
    subtitles: [{ id: "sub_ar", label: "العربية", language: "ar", isDefault: true }],
    audioTracks: [{ id: "aud_en", label: "English", language: "en", isDefault: true }],
  },
];

export const INITIAL_SERIES: Movie[] = [
  {
    id: "tt0903747",
    imdbId: "tt0903747",
    title: "Breaking Bad",
    originalTitle: "Breaking Bad",
    description: "A chemistry teacher diagnosed with inoperable lung cancer turns to manufacturing and selling methamphetamine with a former student in order to secure his family's financial future.",
    backdropUrl: "https://images.metahub.space/background/medium/tt0903747/img",
    posterUrl: "https://images.metahub.space/poster/small/tt0903747/img",
    trailerYoutubeId: "HhesaQXLuRY",
    videoUrl: "",
    duration: "5 Saisons",
    durationSeconds: 3000,
    releaseYear: 2008,
    matchPercentage: 99,
    ageRating: "18+",
    quality: "4K UHD",
    type: "series",
    genres: ["Crime", "Drama", "Thriller"],
    cast: ["Bryan Cranston", "Aaron Paul", "Anna Gunn", "Bob Odenkirk"],
    director: "Vince Gilligan",
    isTrending: true,
    isTop10: true,
    top10Rank: 1,
    episodes: [
      { id: "tt0903747:1:1", season: 1, episode: 1, title: "Épisode 1 : Chute Libre (Pilot)", overview: "Walter White, professeur de chimie, apprend qu'il est atteint d'un cancer incurable.", thumbnail: "https://episodes.metahub.space/tt0903747/1/1/w780.jpg" },
      { id: "tt0903747:1:2", season: 1, episode: 2, title: "Épisode 2 : Le Choix", overview: "Walt et Jesse tentent de se débarrasser des corps dans le camping-car.", thumbnail: "https://episodes.metahub.space/tt0903747/1/2/w780.jpg" },
      { id: "tt0903747:1:3", season: 1, episode: 3, title: "Épisode 3 : Dérapage", overview: "Walt et Jesse nettoient le désordre tandis que Walt fait face à un dilemme moral.", thumbnail: "https://episodes.metahub.space/tt0903747/1/3/w780.jpg" },
      { id: "tt0903747:1:4", season: 1, episode: 4, title: "Épisode 4 : Retour aux Sources", overview: "Walt annonce la nouvelle de son cancer à sa famille réunie.", thumbnail: "https://episodes.metahub.space/tt0903747/1/4/w780.jpg" },
    ],
    subtitles: [
      { id: "sub_ar", label: "العربية (Arabic)", language: "ar", src: "/subtitles/sample_ar.vtt", isDefault: true },
      { id: "sub_fr", label: "Français", language: "fr", src: "/subtitles/sample_fr.vtt" },
      { id: "sub_en", label: "English [CC]", language: "en", src: "/subtitles/sample_en.vtt" },
    ],
    audioTracks: [{ id: "aud_en", label: "English 5.1", language: "en", isDefault: true }],
  },
  {
    id: "tt4574334",
    imdbId: "tt4574334",
    title: "Stranger Things",
    originalTitle: "Stranger Things",
    description: "When a young boy vanishes, a small town uncovers a mystery involving secret experiments, terrifying supernatural forces and one strange little girl with telekinetic powers.",
    backdropUrl: "https://images.metahub.space/background/medium/tt4574334/img",
    posterUrl: "https://images.metahub.space/poster/small/tt4574334/img",
    trailerYoutubeId: "b9EkMc79ZSU",
    videoUrl: "",
    duration: "4 Saisons",
    durationSeconds: 3200,
    releaseYear: 2016,
    matchPercentage: 98,
    ageRating: "16+",
    quality: "4K UHD",
    type: "series",
    genres: ["Drama", "Fantasy", "Horror", "Sci-Fi"],
    cast: ["Millie Bobby Brown", "Finn Wolfhard", "Winona Ryder", "David Harbour"],
    director: "The Duffer Brothers",
    isTrending: true,
    isTop10: true,
    top10Rank: 2,
    episodes: [
      { id: "tt4574334:1:1", season: 1, episode: 1, title: "Chapitre 1 : La Disparition de Will Byers", overview: "Sur le chemin du retour, un jeune garçon voit une créature terrifiante. Une petite fille aux pouvoirs mystérieux fait son apparition.", thumbnail: "https://episodes.metahub.space/tt4574334/1/1/w780.jpg" },
      { id: "tt4574334:1:2", season: 1, episode: 2, title: "Chapitre 2 : La Barjot de Maple Street", overview: "Lucas, Mike et Dustin tentent de communiquer avec la mystérieuse fillette qu'ils ont trouvée dans les bois.", thumbnail: "https://episodes.metahub.space/tt4574334/1/2/w780.jpg" },
    ],
    subtitles: [
      { id: "sub_ar", label: "العربية (Arabic)", language: "ar", src: "/subtitles/sample_ar.vtt", isDefault: true },
      { id: "sub_fr", label: "Français", language: "fr", src: "/subtitles/sample_fr.vtt" },
      { id: "sub_en", label: "English [CC]", language: "en", src: "/subtitles/sample_en.vtt" },
    ],
    audioTracks: [{ id: "aud_en", label: "English [Atmos]", language: "en", isDefault: true }],
  },
  {
    id: "tt0944947",
    imdbId: "tt0944947",
    title: "Game of Thrones",
    originalTitle: "Game of Thrones",
    description: "Nine noble families fight for control over the lands of Westeros, while an ancient enemy returns after being dormant for millennia.",
    backdropUrl: "https://images.metahub.space/background/medium/tt0944947/img",
    posterUrl: "https://images.metahub.space/poster/small/tt0944947/img",
    trailerYoutubeId: "KPLWWIOCOOQ",
    videoUrl: "",
    duration: "8 Saisons",
    durationSeconds: 3600,
    releaseYear: 2011,
    matchPercentage: 99,
    ageRating: "18+",
    quality: "4K UHD",
    type: "series",
    genres: ["Action", "Adventure", "Drama", "Fantasy"],
    cast: ["Emilia Clarke", "Peter Dinklage", "Kit Harington", "Lena Headey"],
    director: "David Benioff, D.B. Weiss",
    isTrending: true,
    isTop10: true,
    top10Rank: 3,
    episodes: [
      { id: "tt0944947:1:1", season: 1, episode: 1, title: "Épisode 1 : L'hiver vient (Winter Is Coming)", overview: "Lord Ned Stark est tiraillé entre sa famille et une requête périlleuse du roi Robert Baratheon.", thumbnail: "https://episodes.metahub.space/tt0944947/1/1/w780.jpg" },
      { id: "tt0944947:1:2", season: 1, episode: 2, title: "Épisode 2 : La Route royale (The Kingsroad)", overview: "Ned Stark part pour Port-Réal avec ses filles tandis que Jon Snow rejoint la Garde de Nuit.", thumbnail: "https://episodes.metahub.space/tt0944947/1/2/w780.jpg" },
    ],
    subtitles: [
      { id: "sub_ar", label: "العربية (Arabic)", language: "ar", src: "/subtitles/sample_ar.vtt", isDefault: true },
      { id: "sub_fr", label: "Français", language: "fr", src: "/subtitles/sample_fr.vtt" },
      { id: "sub_en", label: "English [CC]", language: "en", src: "/subtitles/sample_en.vtt" },
    ],
    audioTracks: [{ id: "aud_en", label: "English 5.1", language: "en", isDefault: true }],
  },
  {
    id: "tt3581920",
    imdbId: "tt3581920",
    title: "The Last of Us",
    originalTitle: "The Last of Us",
    description: "After a global pandemic destroys civilization, a hardened survivor takes charge of a 14-year-old girl who may be humanity's last hope.",
    backdropUrl: "https://images.metahub.space/background/medium/tt3581920/img",
    posterUrl: "https://images.metahub.space/poster/small/tt3581920/img",
    trailerYoutubeId: "uLtkt8BonwM",
    videoUrl: "",
    duration: "1 Saison",
    durationSeconds: 3800,
    releaseYear: 2023,
    matchPercentage: 97,
    ageRating: "18+",
    quality: "4K UHD",
    type: "series",
    genres: ["Action", "Adventure", "Drama", "Sci-Fi"],
    cast: ["Pedro Pascal", "Bella Ramsey", "Gabriel Luna"],
    director: "Craig Mazin, Neil Druckmann",
    isTrending: true,
    isTop10: true,
    top10Rank: 4,
    episodes: [
      { id: "tt3581920:1:1", season: 1, episode: 1, title: "Épisode 1 : Quand on est perdu dans les ténèbres", overview: "Vingt ans après qu'une épidémie fongique a ravagé la planète, les survivants Joel et Tess sont chargés d'une mission.", thumbnail: "https://episodes.metahub.space/tt3581920/1/1/w780.jpg" },
      { id: "tt3581920:1:2", season: 1, episode: 2, title: "Épisode 2 : Les Infectés", overview: "Joel, Tess et Ellie traversent un Boston désolé et inondé pour atteindre leur destination.", thumbnail: "https://episodes.metahub.space/tt3581920/1/2/w780.jpg" },
    ],
    subtitles: [{ id: "sub_ar", label: "العربية", language: "ar", isDefault: true }],
    audioTracks: [{ id: "aud_en", label: "English", language: "en", isDefault: true }],
  },
  {
    id: "tt2442560",
    imdbId: "tt2442560",
    title: "Peaky Blinders",
    originalTitle: "Peaky Blinders",
    description: "A gangster family epic set in 1900s England, centering on a gang who sew razor blades in the peaks of their caps, and their fierce boss Tommy Shelby.",
    backdropUrl: "https://images.metahub.space/background/medium/tt2442560/img",
    posterUrl: "https://images.metahub.space/poster/small/tt2442560/img",
    trailerYoutubeId: "oVzVdvGIC7U",
    videoUrl: "",
    duration: "6 Saisons",
    durationSeconds: 3400,
    releaseYear: 2013,
    matchPercentage: 96,
    ageRating: "18+",
    quality: "4K UHD",
    type: "series",
    genres: ["Crime", "Drama"],
    cast: ["Cillian Murphy", "Paul Anderson", "Helen McCrory", "Tom Hardy"],
    director: "Steven Knight",
    isTrending: true,
    isTop10: true,
    top10Rank: 5,
    episodes: [
      { id: "tt2442560:1:1", season: 1, episode: 1, title: "Épisode 1", overview: "À Birmingham en 1919, Thomas Shelby dirige le redouté gang des Peaky Blinders.", thumbnail: "https://episodes.metahub.space/tt2442560/1/1/w780.jpg" },
      { id: "tt2442560:1:2", season: 1, episode: 2, title: "Épisode 2", overview: "Thomas défie la famille Lee tandis que l'inspecteur Campbell intensifie ses recherches d'armes.", thumbnail: "https://episodes.metahub.space/tt2442560/1/2/w780.jpg" },
    ],
    subtitles: [{ id: "sub_ar", label: "العربية", language: "ar", isDefault: true }],
    audioTracks: [{ id: "aud_en", label: "English", language: "en", isDefault: true }],
  },
  {
    id: "tt12637874",
    imdbId: "tt12637874",
    title: "Fallout",
    originalTitle: "Fallout",
    description: "In a future, post-apocalyptic Los Angeles brought about by nuclear decimation, citizens must live in underground bunkers to protect themselves from radiation, mutants and bandits.",
    backdropUrl: "https://images.metahub.space/background/medium/tt12637874/img",
    posterUrl: "https://images.metahub.space/poster/small/tt12637874/img",
    trailerYoutubeId: "V-mugKDQDlg",
    videoUrl: "",
    duration: "1 Saison",
    durationSeconds: 3600,
    releaseYear: 2024,
    matchPercentage: 97,
    ageRating: "18+",
    quality: "4K UHD",
    type: "series",
    genres: ["Action", "Adventure", "Drama", "Sci-Fi"],
    cast: ["Ella Purnell", "Aaron Moten", "Walton Goggins"],
    director: "Jonathan Nolan",
    isTrending: true,
    isTop10: true,
    top10Rank: 6,
    episodes: [
      { id: "tt12637874:1:1", season: 1, episode: 1, title: "Épisode 1 : La Fin", overview: "Lucy quitte l'abri 33 pour s'aventurer dans un monde de surface désolé et sans pitié.", thumbnail: "https://episodes.metahub.space/tt12637874/1/1/w780.jpg" },
      { id: "tt12637874:1:2", season: 1, episode: 2, title: "Épisode 2 : La Cible", overview: "Lucy rencontre un chercheur en fuite et le redoutable Ghoul.", thumbnail: "https://episodes.metahub.space/tt12637874/1/2/w780.jpg" },
    ],
    subtitles: [{ id: "sub_ar", label: "العربية", language: "ar", isDefault: true }],
    audioTracks: [{ id: "aud_en", label: "English", language: "en", isDefault: true }],
  },
  {
    id: "tt0455275",
    imdbId: "tt0455275",
    title: "Prison Break",
    originalTitle: "Prison Break",
    description: "Due to a political conspiracy, an innocent man is sent to death row and his only hope is his brother, who makes it his mission to deliberately get himself sent to the same prison in order to break the both of them out.",
    backdropUrl: "https://images.metahub.space/background/medium/tt0455275/img",
    posterUrl: "https://images.metahub.space/poster/small/tt0455275/img",
    trailerYoutubeId: "AL9zLctDJaU",
    videoUrl: "",
    duration: "5 Saisons",
    durationSeconds: 2700,
    releaseYear: 2005,
    matchPercentage: 98,
    ageRating: "16+",
    quality: "4K UHD",
    type: "series",
    genres: ["Action", "Crime", "Drama", "Mystery", "Thriller"],
    cast: ["Wentworth Miller", "Dominic Purcell", "Sarah Wayne Callies"],
    director: "Paul Scheuring",
    isTrending: true,
    isTop10: true,
    top10Rank: 7,
    episodes: [
      { id: "tt0455275:1:1", season: 1, episode: 1, title: "Épisode 1 : La Grande Évasion (Pilot)", overview: "Michael Scofield se fait emprisonner délibérément pour sauver son frère Lincoln de la peine de mort.", thumbnail: "https://episodes.metahub.space/tt0455275/1/1/w780.jpg" },
      { id: "tt0455275:1:2", season: 1, episode: 2, title: "Épisode 2 : Allen", overview: "Michael cherche à se procurer un objet crucial auprès de T-Bag et John Abruzzi.", thumbnail: "https://episodes.metahub.space/tt0455275/1/2/w780.jpg" },
    ],
    subtitles: [{ id: "sub_ar", label: "العربية", language: "ar", isDefault: true }],
    audioTracks: [{ id: "aud_en", label: "English", language: "en", isDefault: true }],
  },
  {
    id: "tt2306299",
    imdbId: "tt2306299",
    title: "Vikings",
    originalTitle: "Vikings",
    description: "Vikings transports us to the brutal and mysterious world of Ragnar Lothbrok, a Norse warrior and farmer who yearns to explore—and raid—the distant shores across the ocean.",
    backdropUrl: "https://images.metahub.space/background/medium/tt2306299/img",
    posterUrl: "https://images.metahub.space/poster/small/tt2306299/img",
    trailerYoutubeId: "9GgxinPwAGc",
    videoUrl: "",
    duration: "6 Saisons",
    durationSeconds: 2800,
    releaseYear: 2013,
    matchPercentage: 96,
    ageRating: "18+",
    quality: "4K UHD",
    type: "series",
    genres: ["Action", "Adventure", "Drama", "History"],
    cast: ["Travis Fimmel", "Katheryn Winnick", "Clive Standen", "Gustaf Skarsgård"],
    director: "Michael Hirst",
    isTrending: true,
    isTop10: true,
    top10Rank: 8,
    episodes: [
      { id: "tt2306299:1:1", season: 1, episode: 1, title: "Épisode 1 : Cap à l'Ouest", overview: "Ragnar Lothbrok est convaincu qu'il existe des terres riches à l'ouest et défie son seigneur.", thumbnail: "https://episodes.metahub.space/tt2306299/1/1/w780.jpg" },
      { id: "tt2306299:1:2", season: 1, episode: 2, title: "Épisode 2 : L'Expédition", overview: "Ragnar et ses guerriers naviguent vers l'inconnu et débarquent sur les côtes de Northumbrie.", thumbnail: "https://episodes.metahub.space/tt2306299/1/2/w780.jpg" },
    ],
    subtitles: [{ id: "sub_ar", label: "العربية", language: "ar", isDefault: true }],
    audioTracks: [{ id: "aud_en", label: "English", language: "en", isDefault: true }],
  },
  {
    id: "tt1190634",
    imdbId: "tt1190634",
    title: "The Boys",
    originalTitle: "The Boys",
    description: "A group of vigilantes set out to take down corrupt superheroes who abuse their superpowers instead of using them for good.",
    backdropUrl: "https://images.metahub.space/background/medium/tt1190634/img",
    posterUrl: "https://images.metahub.space/poster/small/tt1190634/img",
    trailerYoutubeId: "06rueu_fh30",
    videoUrl: "",
    duration: "4 Saisons",
    durationSeconds: 3600,
    releaseYear: 2019,
    matchPercentage: 98,
    ageRating: "18+",
    quality: "4K UHD",
    type: "series",
    genres: ["Action", "Comedy", "Crime", "Sci-Fi"],
    cast: ["Karl Urban", "Jack Quaid", "Antony Starr", "Erin Moriarty"],
    director: "Eric Kripke",
    isTrending: true,
    isTop10: true,
    top10Rank: 9,
    episodes: [
      { id: "tt1190634:1:1", season: 1, episode: 1, title: "Épisode 1 : La Règle du Jeu", overview: "Hughie subit une perte dévastatrice causée par un super-héros et rencontre le mystérieux Billy Butcher.", thumbnail: "https://episodes.metahub.space/tt1190634/1/1/w780.jpg" },
      { id: "tt1190634:1:2", season: 1, episode: 2, title: "Épisode 2 : Cerise", overview: "Les Boys capturent Translucide et découvrent la vérité sombre derrière Vought.", thumbnail: "https://episodes.metahub.space/tt1190634/1/2/w780.jpg" },
    ],
    subtitles: [{ id: "sub_ar", label: "العربية", language: "ar", isDefault: true }],
    audioTracks: [{ id: "aud_en", label: "English", language: "en", isDefault: true }],
  },
  {
    id: "tt5753856",
    imdbId: "tt5753856",
    title: "Dark",
    originalTitle: "Dark",
    description: "A family saga with a supernatural twist, set in a German town where the disappearance of two young children exposes the relationships among four families across three generations.",
    backdropUrl: "https://images.metahub.space/background/medium/tt5753856/img",
    posterUrl: "https://images.metahub.space/poster/small/tt5753856/img",
    trailerYoutubeId: "rrwycJ08PSA",
    videoUrl: "",
    duration: "3 Saisons",
    durationSeconds: 3600,
    releaseYear: 2017,
    matchPercentage: 99,
    ageRating: "16+",
    quality: "4K UHD",
    type: "series",
    genres: ["Crime", "Drama", "Mystery", "Sci-Fi", "Thriller"],
    cast: ["Louis Hofmann", "Karoline Eichhorn", "Lisa Vicari"],
    director: "Baran bo Odar",
    isTrending: true,
    isTop10: true,
    top10Rank: 10,
    episodes: [
      { id: "tt5753856:1:1", season: 1, episode: 1, title: "Épisode 1 : Secrets", overview: "En 2019, la disparition d'un adolescent de Winden terrorise la petite ville allemande.", thumbnail: "https://episodes.metahub.space/tt5753856/1/1/w780.jpg" },
      { id: "tt5753856:1:2", season: 1, episode: 2, title: "Épisode 2 : Mensonges", overview: "Un mystérieux corps d'enfant est retrouvé dans la forêt, mais il porte des vêtements des années 80.", thumbnail: "https://episodes.metahub.space/tt5753856/1/2/w780.jpg" },
    ],
    subtitles: [{ id: "sub_ar", label: "العربية", language: "ar", isDefault: true }],
    audioTracks: [{ id: "aud_de", label: "Allemand [Original]", language: "de", isDefault: true }],
  },
];

export const TUNISIAN_MOVIES: Movie[] = [
  {
    id: "tt10499692",
    imdbId: "tt10499692",
    title: "Dachra (دشرة)",
    originalTitle: "Dachra",
    description: "Trois étudiants en journalisme enquêtent sur Mongia, une femme retrouvée mutilée 25 ans plus tôt et soupçonnée de sorcellerie. Leurs investigations les mènent au village isolé et angoissant de Dachra.",
    backdropUrl: "https://images.unsplash.com/photo-1509248961158-e54f6934749c?auto=format&fit=crop&w=1920&q=80",
    posterUrl: "https://images.unsplash.com/photo-1509248961158-e54f6934749c?auto=format&fit=crop&w=600&q=80",
    trailerYoutubeId: "fL0Ew3fTq-w",
    videoUrl: "/sample.mp4",
    duration: "1h 55m",
    durationSeconds: 6900,
    releaseYear: 2018,
    matchPercentage: 97,
    ageRating: "18+",
    quality: "4K UHD",
    type: "movie",
    genres: ["Horreur", "Mystère", "Cinéma Tunisien 🇹🇳"],
    cast: ["Yasmine Dimassi", "Aziz Jbali", "Bilel Slatnia", "Hela Ayed"],
    director: "Abdelhamid Bouchnak",
    isTrending: true,
    subtitles: [
      { id: "sub_ar", label: "العربية (Tunisien)", language: "ar", isDefault: true },
      { id: "sub_fr", label: "Français", language: "fr" },
    ],
    audioTracks: [{ id: "aud_tn", label: "Arabe Tunisien [Original]", language: "ar", isDefault: true }],
  },
  {
    id: "tt_choufly_hal",
    imdbId: "tt7151672",
    title: "Choufly Hal (شوفلي حل)",
    originalTitle: "Choufly Hal",
    description: "La série comique tunisienne culte numéro 1 : les péripéties quotidiennes hilarantes du psychothérapeute Dr Slimane Labyadh et de son frère naïf et attachant Sboui au cœur de Tunis.",
    backdropUrl: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=1920&q=80",
    posterUrl: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=600&q=80",
    trailerYoutubeId: "06rueu_fh30",
    videoUrl: "/sample.mp4",
    duration: "6 Saisons",
    durationSeconds: 2700,
    releaseYear: 2005,
    matchPercentage: 99,
    ageRating: "ALL",
    quality: "HD",
    type: "series",
    genres: ["Comédie", "Famille", "Cinéma Tunisien 🇹🇳"],
    cast: ["Kamel Touati", "Sofiène Chaâri", "Mouna Noureddine", "Jamila Chihi", "Kaouther El Bardi"],
    director: "Slaheddine Essid",
    isTrending: true,
    isFilmFlexOriginal: true,
    episodes: [
      { id: "choufly:1:1", season: 1, episode: 1, title: "Épisode 1 : Le Cabinet du Dr Slimane", overview: "Sboui arrive en panique chez Slimane et bouleverse les rendez-vous des patients.", thumbnail: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=600&q=80" },
      { id: "choufly:1:2", season: 1, episode: 2, title: "Épisode 2 : La Voiture de Fadhila", overview: "Fadhila insiste pour que Sboui apprenne à conduire avec des conséquences comiques.", thumbnail: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=600&q=80" },
      { id: "choufly:1:3", season: 1, episode: 3, title: "Épisode 3 : La Visite de Janet", overview: "Janet débarque à l'immeuble et sème la zizanie entre Sboui et Fadhila.", thumbnail: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=600&q=80" },
      { id: "choufly:1:4", season: 1, episode: 4, title: "Épisode 4 : Le Téléphone Mobile", overview: "Sboui achète son premier téléphone portable et appelle tout le quartier.", thumbnail: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=600&q=80" },
      { id: "choufly:1:5", season: 1, episode: 5, title: "Épisode 5 : L'Anniversaire de Zeineb", overview: "Préparation d'une fête surprise pleine de malentendus chez Dr Slimane.", thumbnail: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=600&q=80" },
    ],
    subtitles: [{ id: "sub_ar", label: "العربية", language: "ar", isDefault: true }],
    audioTracks: [{ id: "aud_tn", label: "Arabe Tunisien", language: "ar", isDefault: true }],
  },
  {
    id: "tt11226168",
    imdbId: "tt11226168",
    title: "Nouba (نوبة)",
    originalTitle: "Nouba",
    description: "Plongeon saisissant dans le Tunis des années 90 et l'univers du Mezwed tunisien, entre amours interdites, fêtes populaires, trahisons et rivalités artistiques intenses.",
    backdropUrl: "https://images.unsplash.com/photo-1517604931442-7e0c8ed2963c?auto=format&fit=crop&w=1920&q=80",
    posterUrl: "https://images.unsplash.com/photo-1517604931442-7e0c8ed2963c?auto=format&fit=crop&w=600&q=80",
    trailerYoutubeId: "uYPbbksJxIg",
    videoUrl: "/sample.mp4",
    duration: "2 Saisons",
    durationSeconds: 3200,
    releaseYear: 2019,
    matchPercentage: 98,
    ageRating: "16+",
    quality: "4K UHD",
    type: "series",
    genres: ["Drame", "Musique", "Cinéma Tunisien 🇹🇳"],
    cast: ["Kamel Touati", "Amira Chebli", "Bahri Rahali", "Chedly Arfaoui", "Bilel Slatnia"],
    director: "Abdelhamid Bouchnak",
    isTrending: true,
    subtitles: [{ id: "sub_ar", label: "العربية", language: "ar", isDefault: true }],
    audioTracks: [{ id: "aud_tn", label: "Arabe Tunisien", language: "ar", isDefault: true }],
  },
  {
    id: "tt0100465",
    imdbId: "tt0100465",
    title: "Halfaouine : Asfour Stah (عصفور السطح)",
    originalTitle: "Halfaouine: Boy of the Terraces",
    description: "À Halfaouine, quartier populaire de Tunis, le jeune Noura découvre le monde secret et fascinant des femmes au bain maure tout en s'éveillant aux mystères de la vie adulte.",
    backdropUrl: "https://images.metahub.space/background/medium/tt0100465/img",
    posterUrl: "https://images.metahub.space/poster/small/tt0100465/img",
    trailerYoutubeId: "Way9Dexny3w",
    videoUrl: "/sample.mp4",
    duration: "1h 38m",
    durationSeconds: 5880,
    releaseYear: 1990,
    matchPercentage: 96,
    ageRating: "16+",
    quality: "HD",
    type: "movie",
    genres: ["Classique", "Comédie", "Drame", "Cinéma Tunisien 🇹🇳"],
    cast: ["Selim Boughedir", "Mustapha Adouani", "Rabia Ben Abdallah"],
    director: "Férid Boughedir",
    subtitles: [
      { id: "sub_ar", label: "العربية", language: "ar", isDefault: true },
      { id: "sub_fr", label: "Français", language: "fr" },
    ],
    audioTracks: [{ id: "aud_tn", label: "Arabe Tunisien", language: "ar", isDefault: true }],
  },
  {
    id: "tt7654388",
    imdbId: "tt7654388",
    title: "El Jaida (الجايدة)",
    originalTitle: "El Jaida",
    description: "En 1955, quelques mois avant l'indépendance de la Tunisie, quatre femmes de différentes générations se retrouvent enfermées à Dar Joued pour insoumission maritale et s'entraident pour conquérir leur liberté.",
    backdropUrl: "https://images.metahub.space/background/medium/tt7654388/img",
    posterUrl: "https://images.metahub.space/poster/small/tt7654388/img",
    trailerYoutubeId: "cqGjhVJWtEg",
    videoUrl: "/sample.mp4",
    duration: "1h 50m",
    durationSeconds: 6600,
    releaseYear: 2017,
    matchPercentage: 95,
    ageRating: "16+",
    quality: "4K UHD",
    type: "movie",
    genres: ["Drame", "Histoire", "Cinéma Tunisien 🇹🇳"],
    cast: ["Fatma Ben Saïdane", "Wajiha Jendoubi", "Souhir Ben Amara", "Salma Mahjoubi"],
    director: "Salma Baccar",
    subtitles: [
      { id: "sub_ar", label: "العربية", language: "ar", isDefault: true },
      { id: "sub_fr", label: "Français", language: "fr" },
    ],
    audioTracks: [{ id: "aud_tn", label: "Arabe Tunisien", language: "ar", isDefault: true }],
  },
  {
    id: "tt5100060",
    imdbId: "tt5100060",
    title: "Nhebbek Hedi (نحبك هادي)",
    originalTitle: "Inhebbek Hedi",
    description: "Hedi, jeune commercial réservé à Kairouan, voit son avenir tracé par sa mère qui prépare son mariage. En mission à Mahdia, il fait la rencontre de Rim et découvre pour la première fois la passion.",
    backdropUrl: "https://images.metahub.space/background/medium/tt5100060/img",
    posterUrl: "https://images.metahub.space/poster/small/tt5100060/img",
    trailerYoutubeId: "Way9Dexny3w",
    videoUrl: "/sample.mp4",
    duration: "1h 33m",
    durationSeconds: 5580,
    releaseYear: 2016,
    matchPercentage: 97,
    ageRating: "16+",
    quality: "4K UHD",
    type: "movie",
    genres: ["Romance", "Drame", "Cinéma Tunisien 🇹🇳"],
    cast: ["Majd Mastoura", "Rym Ben Messaoud", "Sabah Bouzouita"],
    director: "Mohamed Ben Attia",
    subtitles: [
      { id: "sub_ar", label: "العربية", language: "ar", isDefault: true },
      { id: "sub_fr", label: "Français", language: "fr" },
    ],
    audioTracks: [{ id: "aud_tn", label: "Arabe Tunisien", language: "ar", isDefault: true }],
  },
  {
    id: "tt9601140",
    imdbId: "tt9601140",
    title: "Un Divan à Tunis (ع السرير في تونس)",
    originalTitle: "Arab Blues",
    description: "Après avoir exercé en France, Selma rentre ouvrir son cabinet de psychanalyse à Tunis. Confrontée aux démarches administratives et à une clientèle pleine de verve, l'aventure prend une tournure inattendue.",
    backdropUrl: "https://images.metahub.space/background/medium/tt9601140/img",
    posterUrl: "https://images.metahub.space/poster/small/tt9601140/img",
    trailerYoutubeId: "uYPbbksJxIg",
    videoUrl: "/sample.mp4",
    duration: "1h 28m",
    durationSeconds: 5280,
    releaseYear: 2019,
    matchPercentage: 94,
    ageRating: "ALL",
    quality: "4K UHD",
    type: "movie",
    genres: ["Comédie", "Drame", "Cinéma Tunisien 🇹🇳"],
    cast: ["Golshifteh Farahani", "Majd Mastoura", "Aïcha Ben Miled"],
    director: "Manele Labidi",
    subtitles: [
      { id: "sub_ar", label: "العربية", language: "ar", isDefault: true },
      { id: "sub_fr", label: "Français", language: "fr" },
    ],
    audioTracks: [{ id: "aud_fr", label: "Français / Tunisien", language: "fr", isDefault: true }],
  },
];

export const ANIME_MOVIES: Movie[] = [
  {
    id: "tt2560140",
    imdbId: "tt2560140",
    title: "Attack on Titan (L'Attaque des Titans)",
    originalTitle: "Shingeki no Kyojin",
    description: "Dans un monde où l'humanité vit recluse derrière d'immenses murailles pour échapper aux Titans dévoreurs d'hommes, Eren Yeager jure d'éradiquer tous les Titans après la destruction de sa ville natale.",
    backdropUrl: "https://images.metahub.space/background/medium/tt2560140/img",
    posterUrl: "https://images.metahub.space/poster/small/tt2560140/img",
    trailerYoutubeId: "MGRm4IzK1SQ",
    videoUrl: "/sample.mp4",
    duration: "4 Saisons",
    durationSeconds: 1500,
    releaseYear: 2013,
    matchPercentage: 99,
    ageRating: "16+",
    quality: "4K UHD",
    type: "series",
    genres: ["Anime 🎌", "Shonen", "Action", "Dark Fantasy"],
    cast: ["Yuki Kaji", "Yui Ishikawa", "Hiroshi Kamiya"],
    director: "Tetsuro Araki",
    isTrending: true,
    subtitles: [
      { id: "sub_ar", label: "العربية (Arabic)", language: "ar", isDefault: true },
      { id: "sub_fr", label: "Français (French)", language: "fr" },
      { id: "sub_en", label: "English", language: "en" },
    ],
    audioTracks: [
      { id: "aud_ja", label: "Japonais [Original]", language: "ja", isDefault: true },
      { id: "aud_fr", label: "Français [VF]", language: "fr" },
    ],
  },
  {
    id: "tt9335498",
    imdbId: "tt9335498",
    title: "Demon Slayer : Kimetsu no Yaiba",
    originalTitle: "Kimetsu no Yaiba",
    description: "Tanjiro Kamado entreprend un voyage périlleux pour venger sa famille massacrée par un démon et trouver un remède pour sa jeune sœur Nezuko, elle-même transformée en démon.",
    backdropUrl: "https://images.metahub.space/background/medium/tt9335498/img",
    posterUrl: "https://images.metahub.space/poster/small/tt9335498/img",
    trailerYoutubeId: "VQGCKyvzIM4",
    videoUrl: "/sample.mp4",
    duration: "4 Saisons",
    durationSeconds: 1500,
    releaseYear: 2019,
    matchPercentage: 98,
    ageRating: "16+",
    quality: "4K UHD",
    type: "series",
    genres: ["Anime 🎌", "Shonen", "Action", "Fantasy"],
    cast: ["Natsuki Hanae", "Akari Kito", "Hiro Shimono"],
    director: "Haruo Sotozaki",
    isTrending: true,
    subtitles: [
      { id: "sub_ar", label: "العربية (Arabic)", language: "ar", isDefault: true },
      { id: "sub_fr", label: "Français (French)", language: "fr" },
    ],
    audioTracks: [{ id: "aud_ja", label: "Japonais [Original]", language: "ja", isDefault: true }],
  },
  {
    id: "tt12343534",
    imdbId: "tt12343534",
    title: "Jujutsu Kaisen",
    originalTitle: "Jujutsu Kaisen",
    description: "Yuji Itadori avale un doigt maudit contenant l'âme du redoutable Roi des Fléaux Ryomen Sukuna, entrant de force dans le monde secret des exorcistes de Tokyo.",
    backdropUrl: "https://images.metahub.space/background/medium/tt12343534/img",
    posterUrl: "https://images.metahub.space/poster/small/tt12343534/img",
    trailerYoutubeId: "f7_QvIqY1jA",
    videoUrl: "/sample.mp4",
    duration: "2 Saisons",
    durationSeconds: 1500,
    releaseYear: 2020,
    matchPercentage: 99,
    ageRating: "16+",
    quality: "4K UHD",
    type: "series",
    genres: ["Anime 🎌", "Shonen", "Action", "Supernatural"],
    cast: ["Junya Enoki", "Yuma Uchida", "Asami Seto", "Kenjiro Tsuda"],
    director: "Sunghoo Park",
    isTrending: true,
    subtitles: [
      { id: "sub_ar", label: "العربية (Arabic)", language: "ar", isDefault: true },
      { id: "sub_fr", label: "Français (French)", language: "fr" },
    ],
    audioTracks: [{ id: "aud_ja", label: "Japonais [Original]", language: "ja", isDefault: true }],
  },
  {
    id: "tt0388629",
    imdbId: "tt0388629",
    title: "One Piece",
    originalTitle: "One Piece",
    description: "Monkey D. Luffy et l'équipage du Chapeau de Paille sillonnent Grand Line à la recherche du légendaire trésor One Piece pour devenir le prochain Roi des Pirates.",
    backdropUrl: "https://images.metahub.space/background/medium/tt0388629/img",
    posterUrl: "https://images.metahub.space/poster/small/tt0388629/img",
    trailerYoutubeId: "MCb13lbK6fg",
    videoUrl: "/sample.mp4",
    duration: "21 Saisons",
    durationSeconds: 1440,
    releaseYear: 1999,
    matchPercentage: 99,
    ageRating: "13+",
    quality: "HD",
    type: "series",
    genres: ["Anime 🎌", "Shonen", "Aventure", "Action"],
    cast: ["Mayumi Tanaka", "Akemi Okamura", "Kazuya Nakai"],
    director: "Eiichiro Oda",
    isTrending: true,
    subtitles: [
      { id: "sub_ar", label: "العربية (Arabic)", language: "ar", isDefault: true },
      { id: "sub_fr", label: "Français (French)", language: "fr" },
    ],
    audioTracks: [{ id: "aud_ja", label: "Japonais [Original]", language: "ja", isDefault: true }],
  },
  {
    id: "tt21209876",
    imdbId: "tt21209876",
    title: "Solo Leveling",
    originalTitle: "Ore dake Level Up na Ken",
    description: "Dans un monde où des chasseurs aux pouvoirs magiques combattent des monstres mortels, Sung Jin-woo, le chasseur le plus faible du monde, reçoit une quête secrète lui permettant d'augmenter son niveau à l'infini.",
    backdropUrl: "https://images.metahub.space/background/medium/tt21209876/img",
    posterUrl: "https://images.metahub.space/poster/small/tt21209876/img",
    trailerYoutubeId: "916kyW9z1nU",
    videoUrl: "/sample.mp4",
    duration: "1 Saison",
    durationSeconds: 1500,
    releaseYear: 2024,
    matchPercentage: 98,
    ageRating: "16+",
    quality: "4K UHD",
    type: "series",
    genres: ["Anime 🎌", "Action", "Fantasy", "Aventure"],
    cast: ["Taito Ban", "Genta Nakamura", "Reina Ueda"],
    director: "Shunsuke Nakashige",
    isTrending: true,
    subtitles: [
      { id: "sub_ar", label: "العربية (Arabic)", language: "ar", isDefault: true },
      { id: "sub_fr", label: "Français (French)", language: "fr" },
    ],
    audioTracks: [{ id: "aud_ja", label: "Japonais [Original]", language: "ja", isDefault: true }],
  },
  {
    id: "tt0877057",
    imdbId: "tt0877057",
    title: "Death Note",
    originalTitle: "Death Note",
    description: "Light Yagami, brillant lycéen, trouve un carnet capable de tuer toute personne dont le nom y est inscrit. Décidé à purger le monde des criminels, il est traqué par l'énigmatique détective L.",
    backdropUrl: "https://images.metahub.space/background/medium/tt0877057/img",
    posterUrl: "https://images.metahub.space/poster/small/tt0877057/img",
    trailerYoutubeId: "NlJZ-YgAt-c",
    videoUrl: "/sample.mp4",
    duration: "1 Saison",
    durationSeconds: 1400,
    releaseYear: 2006,
    matchPercentage: 99,
    ageRating: "16+",
    quality: "HD",
    type: "series",
    genres: ["Anime 🎌", "Thriller", "Psychologique", "Mystère"],
    cast: ["Mamoru Miyano", "Kappei Yamaguchi", "Shido Nakamura"],
    director: "Tetsuro Araki",
    subtitles: [
      { id: "sub_ar", label: "العربية (Arabic)", language: "ar", isDefault: true },
      { id: "sub_fr", label: "Français (French)", language: "fr" },
    ],
    audioTracks: [{ id: "aud_ja", label: "Japonais [Original]", language: "ja", isDefault: true }],
  },
  {
    id: "tt0245429",
    imdbId: "tt0245429",
    title: "Spirited Away (Le Voyage de Chihiro)",
    originalTitle: "Sen to Chihiro no Kamikakushi",
    description: "Chihiro, une fillette de dix ans, s'aventure dans un monde mystique d'esprits et de divinités dirigé par la sorcière Yubaba, où ses parents sont transformés en porcs.",
    backdropUrl: "https://images.metahub.space/background/medium/tt0245429/img",
    posterUrl: "https://images.metahub.space/poster/small/tt0245429/img",
    trailerYoutubeId: "ByXuk9QqQkk",
    videoUrl: "/sample.mp4",
    duration: "2h 05m",
    durationSeconds: 7500,
    releaseYear: 2001,
    matchPercentage: 99,
    ageRating: "ALL",
    quality: "4K UHD",
    type: "movie",
    genres: ["Anime 🎌", "Animation", "Aventure", "Famille"],
    cast: ["Rumi Hiiragi", "Miyu Irino", "Mari Natsuki"],
    director: "Hayao Miyazaki",
    subtitles: [
      { id: "sub_ar", label: "العربية (Arabic)", language: "ar", isDefault: true },
      { id: "sub_fr", label: "Français (French)", language: "fr" },
    ],
    audioTracks: [{ id: "aud_ja", label: "Japonais [Original]", language: "ja", isDefault: true }],
  },
  {
    id: "tt5311514",
    imdbId: "tt5311514",
    title: "Your Name (Kimi no Na wa)",
    originalTitle: "Kimi no Na wa",
    description: "Mitsuha, une lycéenne de la campagne, et Taki, un lycéen de Tokyo, échangent mystérieusement leurs corps durant leur sommeil et tissent un lien indéfectible à travers le temps et l'espace.",
    backdropUrl: "https://images.metahub.space/background/medium/tt5311514/img",
    posterUrl: "https://images.metahub.space/poster/small/tt5311514/img",
    trailerYoutubeId: "s0wTdCQoc2k",
    videoUrl: "/sample.mp4",
    duration: "1h 46m",
    durationSeconds: 6360,
    releaseYear: 2016,
    matchPercentage: 98,
    ageRating: "ALL",
    quality: "4K UHD",
    type: "movie",
    genres: ["Anime 🎌", "Romance", "Drame", "Fantasy"],
    cast: ["Ryunosuke Kamiki", "Mone Kamishiraishi"],
    director: "Makoto Shinkai",
    subtitles: [
      { id: "sub_ar", label: "العربية (Arabic)", language: "ar", isDefault: true },
      { id: "sub_fr", label: "Français (French)", language: "fr" },
    ],
    audioTracks: [{ id: "aud_ja", label: "Japonais [Original]", language: "ja", isDefault: true }],
  },
];

export const TURKISH_MOVIES: Movie[] = [
  {
    id: "tt10705474",
    imdbId: "tt10705474",
    tmdbId: "95603",
    title: "Kuruluş: Osman (المؤسس عثمان)",
    originalTitle: "Kurulus: Osman",
    description: "Les luttes internes et externes épiques d'Osman Ier et la façon dont il fonde et contrôle l'Empire Ottoman, surmontant trahisons, ennemis mongols et byzantins.",
    backdropUrl: "https://images.metahub.space/background/medium/tt10705474/img",
    posterUrl: "https://images.metahub.space/poster/small/tt10705474/img",
    trailerYoutubeId: "P_zB2eJgQbg",
    videoUrl: "/sample.mp4",
    duration: "5 Saisons",
    durationSeconds: 7200,
    releaseYear: 2019,
    matchPercentage: 99,
    ageRating: "16+",
    quality: "4K UHD",
    type: "series",
    genres: ["Action", "Histoire", "Guerre", "Séries Turques 🇹🇷"],
    cast: ["Burak Özçivit", "Yıldız Çağrı Atiksoy", "Özge Törer"],
    director: "Metin Günay",
    isTrending: true,
    subtitles: [
      { id: "sub_ar", label: "العربية (Traduction)", language: "ar", isDefault: true },
      { id: "sub_fr", label: "Français", language: "fr" },
    ],
    audioTracks: [{ id: "aud_tr", label: "Turc [Original]", language: "tr", isDefault: true }],
  },
  {
    id: "tt21966558",
    imdbId: "tt21966558",
    tmdbId: "209374",
    title: "Yalı Çapkını (طائر الرفراف)",
    originalTitle: "Yali Çapkini",
    description: "Ferit, un jeune séducteur insouciant issu d'une famille d'élite d'Istanbul, se voit forcé par son grand-père d'épouser Seyran, une jeune femme d'Antep, déclenchant passions et tourments.",
    backdropUrl: "https://images.metahub.space/background/medium/tt21966558/img",
    posterUrl: "https://images.metahub.space/poster/small/tt21966558/img",
    trailerYoutubeId: "7X12xQ4g7_U",
    videoUrl: "/sample.mp4",
    duration: "2 Saisons",
    durationSeconds: 7800,
    releaseYear: 2022,
    matchPercentage: 98,
    ageRating: "16+",
    quality: "4K UHD",
    type: "series",
    genres: ["Romance", "Drame", "Séries Turques 🇹🇷"],
    cast: ["Afra Saraçoğlu", "Mert Ramazan Demir", "Çetin Tekindor"],
    director: "Burcu Alptekin",
    isTrending: true,
    subtitles: [
      { id: "sub_ar", label: "العربية", language: "ar", isDefault: true },
      { id: "sub_fr", label: "Français", language: "fr" },
    ],
    audioTracks: [{ id: "aud_tr", label: "Turc [Original]", language: "tr", isDefault: true }],
  },
  {
    id: "tt7380182",
    imdbId: "tt7380182",
    tmdbId: "74866",
    title: "Çukur (الحفرة)",
    originalTitle: "Çukur",
    description: "La famille Koçovalı règne sur Çukur, un quartier dangereux d'Istanbul avec ses propres lois. Lorsque la menace d'un gang rival surgit, le fils prodige Yamaç doit rentrer protéger son clan.",
    backdropUrl: "https://images.metahub.space/background/medium/tt7380182/img",
    posterUrl: "https://images.metahub.space/poster/small/tt7380182/img",
    trailerYoutubeId: "B7M_n_GqRzM",
    videoUrl: "/sample.mp4",
    duration: "4 Saisons",
    durationSeconds: 7500,
    releaseYear: 2017,
    matchPercentage: 99,
    ageRating: "18+",
    quality: "4K UHD",
    type: "series",
    genres: ["Action", "Crime", "Thriller", "Séries Turques 🇹🇷"],
    cast: ["Aras Bulut İynemli", "Erkan Kolçak Köstendil", "Rıza Kocaoğlu"],
    director: "Sinan Öztürk",
    isTrending: true,
    subtitles: [
      { id: "sub_ar", label: "العربية", language: "ar", isDefault: true },
      { id: "sub_fr", label: "Français", language: "fr" },
    ],
    audioTracks: [{ id: "aud_tr", label: "Turc [Original]", language: "tr", isDefault: true }],
  },
  {
    id: "tt4320258",
    imdbId: "tt4320258",
    tmdbId: "66017",
    title: "Diriliş: Ertuğrul (قيامة أرطغرل)",
    originalTitle: "Dirilis: Ertugrul",
    description: "Au XIIIe siècle, le noble guerrier Ertuğrul lutte pour offrir une terre et un avenir à sa tribu Kaya, affrontant Templiers, Mongols et trahisons à l'aube de l'Empire Ottoman.",
    backdropUrl: "https://images.metahub.space/background/medium/tt4320258/img",
    posterUrl: "https://images.metahub.space/poster/small/tt4320258/img",
    trailerYoutubeId: "9Vp1XwZpE6Q",
    videoUrl: "/sample.mp4",
    duration: "5 Saisons",
    durationSeconds: 7200,
    releaseYear: 2014,
    matchPercentage: 99,
    ageRating: "16+",
    quality: "HD",
    type: "series",
    genres: ["Aventure", "Histoire", "Guerre", "Séries Turques 🇹🇷"],
    cast: ["Engin Altan Düzyatan", "Hülya Darcan", "Esra Bilgiç"],
    director: "Metin Günay",
    subtitles: [
      { id: "sub_ar", label: "العربية", language: "ar", isDefault: true },
      { id: "sub_fr", label: "Français", language: "fr" },
    ],
    audioTracks: [{ id: "aud_tr", label: "Turc [Original]", language: "tr", isDefault: true }],
  },
  {
    id: "tt12439466",
    imdbId: "tt12439466",
    tmdbId: "104877",
    title: "Sen Çal Kapımı (أنت اطرق بابي)",
    originalTitle: "Sen Çal Kapimi",
    description: "Eda Yıldız, étudiante brillante, voit sa bourse internationale supprimée par le séduisant architecte Serkan Bolat. Il lui propose un faux fiancé pendant deux mois en échange de ses études.",
    backdropUrl: "https://images.metahub.space/background/medium/tt12439466/img",
    posterUrl: "https://images.metahub.space/poster/small/tt12439466/img",
    trailerYoutubeId: "N1o9E2ZlU2w",
    videoUrl: "/sample.mp4",
    duration: "2 Saisons",
    durationSeconds: 7200,
    releaseYear: 2020,
    matchPercentage: 97,
    ageRating: "13+",
    quality: "4K UHD",
    type: "series",
    genres: ["Comédie", "Romance", "Séries Turques 🇹🇷"],
    cast: ["Hande Erçel", "Kerem Bürsin", "Neslihan Yeldan"],
    director: "Altan Dönmez",
    subtitles: [
      { id: "sub_ar", label: "العربية", language: "ar", isDefault: true },
      { id: "sub_fr", label: "Français", language: "fr" },
    ],
    audioTracks: [{ id: "aud_tr", label: "Turc [Original]", language: "tr", isDefault: true }],
  },
  {
    id: "tt22340578",
    imdbId: "tt22340578",
    tmdbId: "211174",
    title: "Kızılcık Şerbeti (شراب التوت)",
    originalTitle: "Kizilcik Serbeti",
    description: "L'union amoureuse de Doğa et Fatih réunit deux familles turques aux modes de vie et valeurs diamétralement opposés, déclenchant conflits sociaux et drames intimes poignants.",
    backdropUrl: "https://images.metahub.space/background/medium/tt22340578/img",
    posterUrl: "https://images.metahub.space/poster/small/tt22340578/img",
    trailerYoutubeId: "8bJmP_N9xGk",
    videoUrl: "/sample.mp4",
    duration: "2 Saisons",
    durationSeconds: 7500,
    releaseYear: 2022,
    matchPercentage: 96,
    ageRating: "16+",
    quality: "4K UHD",
    type: "series",
    genres: ["Drame", "Famille", "Séries Turques 🇹🇷"],
    cast: ["Barış Kılıç", "Evrim Alasya", "Sıla Türkoğlu", "Doğukan Güngör"],
    director: "Ketche",
    subtitles: [
      { id: "sub_ar", label: "العربية", language: "ar", isDefault: true },
      { id: "sub_fr", label: "Français", language: "fr" },
    ],
    audioTracks: [{ id: "aud_tr", label: "Turc [Original]", language: "tr", isDefault: true }],
  },
  {
    id: "tt10431500",
    imdbId: "tt10431500",
    tmdbId: "615952",
    title: "Miracle in Cell No. 7 (معجزة في الزنزانة 7)",
    originalTitle: "7. Kogustaki Mucize",
    description: "Memo, un père handicapé mental séparé de sa petite fille Ova, est injustement condamné à mort pour le meurtre d'une fillette de commandant. Ses compagnons de cellule vont tenter l'impossible.",
    backdropUrl: "https://images.metahub.space/background/medium/tt10431500/img",
    posterUrl: "https://images.metahub.space/poster/small/tt10431500/img",
    trailerYoutubeId: "mX4R8E1l2_c",
    videoUrl: "/sample.mp4",
    duration: "2h 12m",
    durationSeconds: 7920,
    releaseYear: 2019,
    matchPercentage: 99,
    ageRating: "16+",
    quality: "4K UHD",
    type: "movie",
    genres: ["Drame", "Famille", "Cinéma Turc 🇹🇷"],
    cast: ["Aras Bulut İynemli", "Nisa Sofiya Aksongur", "Deniz Baysal"],
    director: "Mehmet Ada Öztekin",
    subtitles: [
      { id: "sub_ar", label: "العربية (Traduction)", language: "ar", isDefault: true },
      { id: "sub_fr", label: "Français", language: "fr" },
    ],
    audioTracks: [{ id: "aud_tr", label: "Turc [Original]", language: "tr", isDefault: true }],
  },
  {
    id: "tt5030248",
    imdbId: "tt5030248",
    tmdbId: "64551",
    title: "Kara Sevda (حب أعمى)",
    originalTitle: "Kara Sevda",
    description: "Kemal, issu d'une famille modeste, et Nihan, issue d'une famille aisée, vivent un amour passionné jusqu'au jour où un chantage force Nihan à épouser le riche et possessif Emir.",
    backdropUrl: "https://images.metahub.space/background/medium/tt5030248/img",
    posterUrl: "https://images.metahub.space/poster/small/tt5030248/img",
    trailerYoutubeId: "T7u9gP6k_Bw",
    videoUrl: "/sample.mp4",
    duration: "2 Saisons",
    durationSeconds: 7200,
    releaseYear: 2015,
    matchPercentage: 98,
    ageRating: "16+",
    quality: "HD",
    type: "series",
    genres: ["Romance", "Drame", "Mystère", "Séries Turques 🇹🇷"],
    cast: ["Burak Özçivit", "Neslihan Atagül", "Kaan Urgancıoğlu"],
    director: "Hilal Saral",
    subtitles: [
      { id: "sub_ar", label: "العربية", language: "ar", isDefault: true },
      { id: "sub_fr", label: "Français", language: "fr" },
    ],
    audioTracks: [{ id: "aud_tr", label: "Turc [Original]", language: "tr", isDefault: true }],
  },
  {
    id: "tt15330386",
    imdbId: "tt15330386",
    tmdbId: "134049",
    title: "Yargı (القضاء)",
    originalTitle: "Yargi",
    description: "Ilgaz, un procureur respecté et intègre, et Ceylin, une avocate audacieuse prête à contourner les règles, voient leurs chemins se croiser sur une affaire de meurtre complexe liée à leurs propres familles.",
    backdropUrl: "https://images.metahub.space/background/medium/tt15330386/img",
    posterUrl: "https://images.metahub.space/poster/small/tt15330386/img",
    trailerYoutubeId: "F1x5P8mR2_A",
    videoUrl: "/sample.mp4",
    duration: "3 Saisons",
    durationSeconds: 7800,
    releaseYear: 2021,
    matchPercentage: 97,
    ageRating: "16+",
    quality: "4K UHD",
    type: "series",
    genres: ["Crime", "Mystère", "Drame", "Séries Turques 🇹🇷"],
    cast: ["Kaan Urgancıoğlu", "Pınar Deniz", "Hüseyin Avni Danyal"],
    director: "Ali Bilgin",
    subtitles: [
      { id: "sub_ar", label: "العربية", language: "ar", isDefault: true },
      { id: "sub_fr", label: "Français", language: "fr" },
    ],
    audioTracks: [{ id: "aud_tr", label: "Turc [Original]", language: "tr", isDefault: true }],
  },
];

