import { Movie, Profile } from "@/types";

export const DEFAULT_PROFILES: Profile[] = [
  {
    id: "profile_1",
    name: "VIP Member",
    avatar: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=200&h=200&q=80",
    pinCode: "", // No PIN by default, can be set
    isKids: false,
  },
  {
    id: "profile_2",
    name: "Family / Kids",
    avatar: "https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?auto=format&fit=crop&w=200&h=200&q=80",
    pinCode: "1234", // Sample PIN locked profile
    isKids: true,
  },
];

export const INITIAL_MOVIES: Movie[] = [
  {
    id: "m_dune2",
    imdbId: "tt15239678",
    title: "Dune: Part Two",
    originalTitle: "Dune: Part Two",
    description: "Paul Atreides unites with Chani and the Fremen while seeking revenge against the conspirators who destroyed his family. Facing a choice between the love of his life and the fate of the universe, he endeavors to prevent a terrible future.",
    backdropUrl: "https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=1920&q=80",
    posterUrl: "https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=600&q=80",
    trailerYoutubeId: "Way9Dexny3w",
    videoUrl: "/sample.mp4",
    duration: "2h 46m",
    durationSeconds: 9960,
    releaseYear: 2024,
    matchPercentage: 99,
    ageRating: "16+",
    quality: "4K UHD",
    genres: ["Sci-Fi", "Adventure", "Action"],
    cast: ["Timothée Chalamet", "Zendaya", "Rebecca Ferguson", "Javier Bardem"],
    director: "Denis Villeneuve",
    isTrending: true,
    isTop10: true,
    top10Rank: 1,
    isFilmFlexOriginal: true,
    subtitles: [
      { id: "sub_ar", label: "العربية (Arabic)", language: "ar", src: "/subtitles/sample_ar.vtt", isDefault: true },
      { id: "sub_fr", label: "Français (French)", language: "fr", src: "/subtitles/sample_fr.vtt" },
      { id: "sub_en", label: "English [CC]", language: "en", src: "/subtitles/sample_en.vtt" },
    ],
    audioTracks: [
      { id: "aud_en", label: "English - Dolby Atmos 5.1", language: "en", isDefault: true },
      { id: "aud_fr", label: "Français - Doublage", language: "fr" },
    ],
  },
  {
    id: "m_oppenheimer",
    imdbId: "tt15398776",
    title: "Oppenheimer",
    originalTitle: "Oppenheimer",
    description: "The story of American scientist J. Robert Oppenheimer and his role in the development of the atomic bomb during World War II, exploring the moral paradoxes and political fallout.",
    backdropUrl: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=1920&q=80",
    posterUrl: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=600&q=80",
    trailerYoutubeId: "uYPbbksJxIg",
    videoUrl: "/sample.mp4",
    duration: "3h 00m",
    durationSeconds: 10800,
    releaseYear: 2023,
    matchPercentage: 98,
    ageRating: "18+",
    quality: "4K UHD",
    genres: ["Biography", "Drama", "History"],
    cast: ["Cillian Murphy", "Emily Blunt", "Matt Damon", "Robert Downey Jr."],
    director: "Christopher Nolan",
    isTrending: true,
    isTop10: true,
    top10Rank: 2,
    subtitles: [
      { id: "sub_ar", label: "العربية (Arabic)", language: "ar", src: "/subtitles/sample_ar.vtt", isDefault: true },
      { id: "sub_fr", label: "Français (French)", language: "fr", src: "/subtitles/sample_fr.vtt" },
      { id: "sub_en", label: "English [CC]", language: "en", src: "/subtitles/sample_en.vtt" },
    ],
    audioTracks: [
      { id: "aud_en", label: "English - Original 5.1", language: "en", isDefault: true },
      { id: "aud_fr", label: "Français - VFF", language: "fr" },
    ],
  },
  {
    id: "m_spiderverse",
    imdbId: "tt9362722",
    title: "Spider-Man: Across the Spider-Verse",
    originalTitle: "Spider-Man: Across the Spider-Verse",
    description: "Miles Morales catapults across the Multiverse, where he encounters a team of Spider-People charged with protecting its very existence. When heroes clash, Miles must redefine what it means to be a hero.",
    backdropUrl: "https://images.unsplash.com/photo-1635805737707-575885ab0820?auto=format&fit=crop&w=1920&q=80",
    posterUrl: "https://images.unsplash.com/photo-1635805737707-575885ab0820?auto=format&fit=crop&w=600&q=80",
    trailerYoutubeId: "cqGjhVJWtEg",
    videoUrl: "/sample.mp4",
    duration: "2h 20m",
    durationSeconds: 8400,
    releaseYear: 2023,
    matchPercentage: 97,
    ageRating: "13+",
    quality: "4K UHD",
    genres: ["Animation", "Action", "Adventure"],
    cast: ["Shameik Moore", "Hailee Steinfeld", "Oscar Isaac"],
    director: "Joaquim Dos Santos, Kemp Powers",
    isTrending: true,
    isTop10: true,
    top10Rank: 3,
    subtitles: [
      { id: "sub_ar", label: "العربية (Arabic)", language: "ar", src: "/subtitles/sample_ar.vtt", isDefault: true },
      { id: "sub_fr", label: "Français (French)", language: "fr", src: "/subtitles/sample_fr.vtt" },
      { id: "sub_en", label: "English [CC]", language: "en", src: "/subtitles/sample_en.vtt" },
    ],
    audioTracks: [
      { id: "aud_en", label: "English - Original", language: "en", isDefault: true },
      { id: "aud_fr", label: "Français", language: "fr" },
    ],
  },
  {
    id: "m_inception",
    imdbId: "tt1375666",
    title: "Inception",
    originalTitle: "Inception",
    description: "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O., but his tragic past may doom the project.",
    backdropUrl: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=1920&q=80",
    posterUrl: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=600&q=80",
    trailerYoutubeId: "YoHD9XEInc0",
    videoUrl: "/sample.mp4",
    duration: "2h 28m",
    durationSeconds: 8880,
    releaseYear: 2010,
    matchPercentage: 99,
    ageRating: "13+",
    quality: "4K UHD",
    genres: ["Action", "Sci-Fi", "Thriller"],
    cast: ["Leonardo DiCaprio", "Joseph Gordon-Levitt", "Elliot Page"],
    director: "Christopher Nolan",
    isTop10: true,
    top10Rank: 4,
    subtitles: [
      { id: "sub_ar", label: "العربية (Arabic)", language: "ar", src: "/subtitles/sample_ar.vtt", isDefault: true },
      { id: "sub_fr", label: "Français", language: "fr", src: "/subtitles/sample_fr.vtt" },
      { id: "sub_en", label: "English [CC]", language: "en", src: "/subtitles/sample_en.vtt" },
    ],
    audioTracks: [
      { id: "aud_en", label: "English [Original]", language: "en", isDefault: true },
      { id: "aud_fr", label: "Français", language: "fr" },
    ],
  },
  {
    id: "m_dark_knight",
    imdbId: "tt0468569",
    title: "The Dark Knight",
    originalTitle: "The Dark Knight",
    description: "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.",
    backdropUrl: "https://images.unsplash.com/photo-1509248961158-e54f6934749c?auto=format&fit=crop&w=1920&q=80",
    posterUrl: "https://images.unsplash.com/photo-1509248961158-e54f6934749c?auto=format&fit=crop&w=600&q=80",
    trailerYoutubeId: "EXeTwQWrcwY",
    videoUrl: "/sample.mp4",
    duration: "2h 32m",
    durationSeconds: 9120,
    releaseYear: 2008,
    matchPercentage: 99,
    ageRating: "16+",
    quality: "4K UHD",
    genres: ["Action", "Crime", "Drama"],
    cast: ["Christian Bale", "Heath Ledger", "Aaron Eckhart"],
    director: "Christopher Nolan",
    isTop10: true,
    top10Rank: 5,
    subtitles: [
      { id: "sub_ar", label: "العربية (Arabic)", language: "ar", src: "/subtitles/sample_ar.vtt", isDefault: true },
      { id: "sub_fr", label: "Français", language: "fr", src: "/subtitles/sample_fr.vtt" },
    ],
    audioTracks: [
      { id: "aud_en", label: "English [Original]", language: "en", isDefault: true },
      { id: "aud_fr", label: "Français", language: "fr" },
    ],
  },
  {
    id: "m_interstellar",
    imdbId: "tt0816692",
    title: "Interstellar",
    originalTitle: "Interstellar",
    description: "When Earth becomes uninhabitable in the future, a farmer and ex-NASA pilot, Joseph Cooper, is tasked to pilot a spacecraft, along with a team of researchers, to find a new planet for humans.",
    backdropUrl: "https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?auto=format&fit=crop&w=1920&q=80",
    posterUrl: "https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?auto=format&fit=crop&w=600&q=80",
    trailerYoutubeId: "zSWdZVtXT7E",
    videoUrl: "/sample.mp4",
    duration: "2h 49m",
    durationSeconds: 10140,
    releaseYear: 2014,
    matchPercentage: 98,
    ageRating: "13+",
    quality: "4K UHD",
    genres: ["Sci-Fi", "Adventure", "Drama"],
    cast: ["Matthew McConaughey", "Anne Hathaway", "Jessica Chastain"],
    director: "Christopher Nolan",
    isTop10: true,
    top10Rank: 6,
    subtitles: [
      { id: "sub_ar", label: "العربية (Arabic)", language: "ar", src: "/subtitles/sample_ar.vtt", isDefault: true },
      { id: "sub_fr", label: "Français", language: "fr", src: "/subtitles/sample_fr.vtt" },
    ],
    audioTracks: [
      { id: "aud_en", label: "English - DTS", language: "en", isDefault: true },
    ],
  },
  {
    id: "m_stranger_things",
    imdbId: "tt4574334",
    title: "Stranger Things",
    originalTitle: "Stranger Things",
    description: "When a young boy vanishes, a small town uncovers a mystery involving secret experiments, terrifying supernatural forces and one strange little girl.",
    backdropUrl: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=1920&q=80",
    posterUrl: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=600&q=80",
    trailerYoutubeId: "b9EkMc79ZSU",
    videoUrl: "/sample.mp4",
    duration: "4 Seasons",
    durationSeconds: 3600,
    releaseYear: 2022,
    matchPercentage: 96,
    ageRating: "16+",
    quality: "HDR",
    genres: ["Sci-Fi", "Horror", "Drama"],
    cast: ["Millie Bobby Brown", "Finn Wolfhard", "Winona Ryder"],
    isFilmFlexOriginal: true,
    isTrending: true,
    isTop10: true,
    top10Rank: 7,
    subtitles: [
      { id: "sub_ar", label: "العربية (Arabic)", language: "ar", src: "/subtitles/sample_ar.vtt", isDefault: true },
      { id: "sub_fr", label: "Français", language: "fr", src: "/subtitles/sample_fr.vtt" },
    ],
    audioTracks: [{ id: "aud_en", label: "English", language: "en", isDefault: true }],
  },
  {
    id: "m_cyberpunk",
    imdbId: "tt12590266",
    title: "Cyberpunk: Edgerunners",
    originalTitle: "Cyberpunk: Edgerunners",
    description: "A street kid trying to survive in a technology and body modification-obsessed city of the future. Having everything to lose, he chooses to stay alive by becoming an edgerunner.",
    backdropUrl: "https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&w=1920&q=80",
    posterUrl: "https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&w=600&q=80",
    trailerYoutubeId: "JtqIas3bYhg",
    videoUrl: "/sample.mp4",
    duration: "10 Episodes",
    durationSeconds: 1500,
    releaseYear: 2022,
    matchPercentage: 97,
    ageRating: "18+",
    quality: "4K UHD",
    genres: ["Animation", "Action", "Sci-Fi"],
    cast: ["KENN", "Aoi Yuuki", "Hiroki Touchi"],
    isTrending: true,
    isTop10: true,
    top10Rank: 8,
    subtitles: [
      { id: "sub_ar", label: "العربية (Arabic)", language: "ar", src: "/subtitles/sample_ar.vtt", isDefault: true },
      { id: "sub_fr", label: "Français", language: "fr", src: "/subtitles/sample_fr.vtt" },
    ],
    audioTracks: [
      { id: "aud_ja", label: "Japanese [Original]", language: "ja", isDefault: true },
      { id: "aud_en", label: "English", language: "en" },
    ],
  },
  {
    id: "m_john_wick_4",
    imdbId: "tt10366206",
    title: "John Wick: Chapter 4",
    originalTitle: "John Wick: Chapter 4",
    description: "John Wick uncovers a path to defeating The High Table. But before he can earn his freedom, Wick must face off against a new enemy with powerful alliances across the globe.",
    backdropUrl: "https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?auto=format&fit=crop&w=1920&q=80",
    posterUrl: "https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?auto=format&fit=crop&w=600&q=80",
    trailerYoutubeId: "qEVUtrk8_B4",
    videoUrl: "/sample.mp4",
    duration: "2h 49m",
    durationSeconds: 10140,
    releaseYear: 2023,
    matchPercentage: 95,
    ageRating: "18+",
    quality: "4K UHD",
    genres: ["Action", "Crime", "Thriller"],
    cast: ["Keanu Reeves", "Donnie Yen", "Bill Skarsgård"],
    director: "Chad Stahelski",
    isTop10: true,
    top10Rank: 9,
    subtitles: [
      { id: "sub_ar", label: "العربية (Arabic)", language: "ar", src: "/subtitles/sample_ar.vtt", isDefault: true },
      { id: "sub_fr", label: "Français", language: "fr", src: "/subtitles/sample_fr.vtt" },
    ],
    audioTracks: [{ id: "aud_en", label: "English", language: "en", isDefault: true }],
  },
  {
    id: "m_gladiator_2",
    imdbId: "tt9660502",
    title: "Gladiator II",
    originalTitle: "Gladiator II",
    description: "Years after witnessing the death of the revered hero Maximus at the hands of his uncle, Lucius must enter the Colosseum after his home is conquered by the tyrannical Emperors who now lead Rome.",
    backdropUrl: "https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?auto=format&fit=crop&w=1920&q=80",
    posterUrl: "https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?auto=format&fit=crop&w=600&q=80",
    trailerYoutubeId: "4rgYUipGJNo",
    videoUrl: "/sample.mp4",
    duration: "2h 28m",
    durationSeconds: 8880,
    releaseYear: 2024,
    matchPercentage: 94,
    ageRating: "16+",
    quality: "4K UHD",
    genres: ["Action", "Adventure", "Drama"],
    cast: ["Paul Mescal", "Pedro Pascal", "Denzel Washington"],
    director: "Ridley Scott",
    isTop10: true,
    top10Rank: 10,
    subtitles: [
      { id: "sub_ar", label: "العربية (Arabic)", language: "ar", src: "/subtitles/sample_ar.vtt", isDefault: true },
      { id: "sub_fr", label: "Français", language: "fr", src: "/subtitles/sample_fr.vtt" },
    ],
    audioTracks: [{ id: "aud_en", label: "English", language: "en", isDefault: true }],
  },
];

export const INITIAL_SERIES: Movie[] = [
  {
    id: "tt0903747",
    imdbId: "tt0903747",
    title: "Breaking Bad",
    originalTitle: "Breaking Bad",
    description: "A chemistry teacher diagnosed with inoperable lung cancer turns to manufacturing and selling methamphetamine with a former student in order to secure his family's financial future.",
    backdropUrl: "https://images.metahub.space/background/medium/tt0903747/img",
    posterUrl: "https://images.metahub.space/poster/small/tt0903747/img",
    trailerYoutubeId: "HhesaQXLuRY",
    videoUrl: "",
    duration: "5 Saisons",
    durationSeconds: 3000,
    releaseYear: 2008,
    matchPercentage: 99,
    ageRating: "18+",
    quality: "4K UHD",
    type: "series",
    genres: ["Crime", "Drama", "Thriller"],
    cast: ["Bryan Cranston", "Aaron Paul", "Anna Gunn", "Bob Odenkirk"],
    director: "Vince Gilligan",
    isTrending: true,
    isTop10: true,
    top10Rank: 1,
    episodes: [
      { id: "tt0903747:1:1", season: 1, episode: 1, title: "Épisode 1 : Chute Libre (Pilot)", overview: "Walter White, professeur de chimie, apprend qu'il est atteint d'un cancer incurable.", thumbnail: "https://episodes.metahub.space/tt0903747/1/1/w780.jpg" },
      { id: "tt0903747:1:2", season: 1, episode: 2, title: "Épisode 2 : Le Choix", overview: "Walt et Jesse tentent de se débarrasser des corps dans le camping-car.", thumbnail: "https://episodes.metahub.space/tt0903747/1/2/w780.jpg" },
      { id: "tt0903747:1:3", season: 1, episode: 3, title: "Épisode 3 : Dérapage", overview: "Walt et Jesse nettoient le désordre tandis que Walt fait face à un dilemme moral.", thumbnail: "https://episodes.metahub.space/tt0903747/1/3/w780.jpg" },
      { id: "tt0903747:1:4", season: 1, episode: 4, title: "Épisode 4 : Retour aux Sources", overview: "Walt annonce la nouvelle de son cancer à sa famille réunie.", thumbnail: "https://episodes.metahub.space/tt0903747/1/4/w780.jpg" },
    ],
    subtitles: [
      { id: "sub_ar", label: "العربية (Arabic)", language: "ar", src: "/subtitles/sample_ar.vtt", isDefault: true },
      { id: "sub_fr", label: "Français", language: "fr", src: "/subtitles/sample_fr.vtt" },
      { id: "sub_en", label: "English [CC]", language: "en", src: "/subtitles/sample_en.vtt" },
    ],
    audioTracks: [{ id: "aud_en", label: "English 5.1", language: "en", isDefault: true }],
  },
  {
    id: "tt4574334",
    imdbId: "tt4574334",
    title: "Stranger Things",
    originalTitle: "Stranger Things",
    description: "When a young boy vanishes, a small town uncovers a mystery involving secret experiments, terrifying supernatural forces and one strange little girl with telekinetic powers.",
    backdropUrl: "https://images.metahub.space/background/medium/tt4574334/img",
    posterUrl: "https://images.metahub.space/poster/small/tt4574334/img",
    trailerYoutubeId: "b9EkMc79ZSU",
    videoUrl: "",
    duration: "4 Saisons",
    durationSeconds: 3200,
    releaseYear: 2016,
    matchPercentage: 98,
    ageRating: "16+",
    quality: "4K UHD",
    type: "series",
    genres: ["Drama", "Fantasy", "Horror", "Sci-Fi"],
    cast: ["Millie Bobby Brown", "Finn Wolfhard", "Winona Ryder", "David Harbour"],
    director: "The Duffer Brothers",
    isTrending: true,
    isTop10: true,
    top10Rank: 2,
    episodes: [
      { id: "tt4574334:1:1", season: 1, episode: 1, title: "Chapitre 1 : La Disparition de Will Byers", overview: "Sur le chemin du retour, un jeune garçon voit une créature terrifiante. Une petite fille aux pouvoirs mystérieux fait son apparition.", thumbnail: "https://episodes.metahub.space/tt4574334/1/1/w780.jpg" },
      { id: "tt4574334:1:2", season: 1, episode: 2, title: "Chapitre 2 : La Barjot de Maple Street", overview: "Lucas, Mike et Dustin tentent de communiquer avec la mystérieuse fillette qu'ils ont trouvée dans les bois.", thumbnail: "https://episodes.metahub.space/tt4574334/1/2/w780.jpg" },
    ],
    subtitles: [
      { id: "sub_ar", label: "العربية (Arabic)", language: "ar", src: "/subtitles/sample_ar.vtt", isDefault: true },
      { id: "sub_fr", label: "Français", language: "fr", src: "/subtitles/sample_fr.vtt" },
      { id: "sub_en", label: "English [CC]", language: "en", src: "/subtitles/sample_en.vtt" },
    ],
    audioTracks: [{ id: "aud_en", label: "English [Atmos]", language: "en", isDefault: true }],
  },
  {
    id: "tt0944947",
    imdbId: "tt0944947",
    title: "Game of Thrones",
    originalTitle: "Game of Thrones",
    description: "Nine noble families fight for control over the lands of Westeros, while an ancient enemy returns after being dormant for millennia.",
    backdropUrl: "https://images.metahub.space/background/medium/tt0944947/img",
    posterUrl: "https://images.metahub.space/poster/small/tt0944947/img",
    trailerYoutubeId: "KPLWWIOCOOQ",
    videoUrl: "",
    duration: "8 Saisons",
    durationSeconds: 3600,
    releaseYear: 2011,
    matchPercentage: 99,
    ageRating: "18+",
    quality: "4K UHD",
    type: "series",
    genres: ["Action", "Adventure", "Drama", "Fantasy"],
    cast: ["Emilia Clarke", "Peter Dinklage", "Kit Harington", "Lena Headey"],
    director: "David Benioff, D.B. Weiss",
    isTrending: true,
    isTop10: true,
    top10Rank: 3,
    episodes: [
      { id: "tt0944947:1:1", season: 1, episode: 1, title: "Épisode 1 : L'hiver vient (Winter Is Coming)", overview: "Lord Ned Stark est tiraillé entre sa famille et une requête périlleuse du roi Robert Baratheon.", thumbnail: "https://episodes.metahub.space/tt0944947/1/1/w780.jpg" },
      { id: "tt0944947:1:2", season: 1, episode: 2, title: "Épisode 2 : La Route royale (The Kingsroad)", overview: "Ned Stark part pour Port-Réal avec ses filles tandis que Jon Snow rejoint la Garde de Nuit.", thumbnail: "https://episodes.metahub.space/tt0944947/1/2/w780.jpg" },
    ],
    subtitles: [
      { id: "sub_ar", label: "العربية (Arabic)", language: "ar", src: "/subtitles/sample_ar.vtt", isDefault: true },
      { id: "sub_fr", label: "Français", language: "fr", src: "/subtitles/sample_fr.vtt" },
      { id: "sub_en", label: "English [CC]", language: "en", src: "/subtitles/sample_en.vtt" },
    ],
    audioTracks: [{ id: "aud_en", label: "English 5.1", language: "en", isDefault: true }],
  },
  {
    id: "tt3581920",
    imdbId: "tt3581920",
    title: "The Last of Us",
    originalTitle: "The Last of Us",
    description: "After a global pandemic destroys civilization, a hardened survivor takes charge of a 14-year-old girl who may be humanity's last hope.",
    backdropUrl: "https://images.metahub.space/background/medium/tt3581920/img",
    posterUrl: "https://images.metahub.space/poster/small/tt3581920/img",
    trailerYoutubeId: "uLtkt8BonwM",
    videoUrl: "",
    duration: "1 Saison",
    durationSeconds: 3800,
    releaseYear: 2023,
    matchPercentage: 97,
    ageRating: "18+",
    quality: "4K UHD",
    type: "series",
    genres: ["Action", "Adventure", "Drama", "Sci-Fi"],
    cast: ["Pedro Pascal", "Bella Ramsey", "Gabriel Luna"],
    director: "Craig Mazin, Neil Druckmann",
    isTrending: true,
    isTop10: true,
    top10Rank: 4,
    episodes: [
      { id: "tt3581920:1:1", season: 1, episode: 1, title: "Épisode 1 : Quand on est perdu dans les ténèbres", overview: "Vingt ans après qu'une épidémie fongique a ravagé la planète, les survivants Joel et Tess sont chargés d'une mission.", thumbnail: "https://episodes.metahub.space/tt3581920/1/1/w780.jpg" },
      { id: "tt3581920:1:2", season: 1, episode: 2, title: "Épisode 2 : Les Infectés", overview: "Joel, Tess et Ellie traversent un Boston désolé et inondé pour atteindre leur destination.", thumbnail: "https://episodes.metahub.space/tt3581920/1/2/w780.jpg" },
    ],
    subtitles: [
      { id: "sub_ar", label: "العربية (Arabic)", language: "ar", src: "/subtitles/sample_ar.vtt", isDefault: true },
      { id: "sub_fr", label: "Français", language: "fr", src: "/subtitles/sample_fr.vtt" },
      { id: "sub_en", label: "English [CC]", language: "en", src: "/subtitles/sample_en.vtt" },
    ],
    audioTracks: [{ id: "aud_en", label: "English [Original]", language: "en", isDefault: true }],
  },
  {
    id: "tt2442560",
    imdbId: "tt2442560",
    title: "Peaky Blinders",
    originalTitle: "Peaky Blinders",
    description: "A gangster family epic set in 1900s England, centering on a gang who sew razor blades in the peaks of their caps, and their fierce boss Tommy Shelby.",
    backdropUrl: "https://images.metahub.space/background/medium/tt2442560/img",
    posterUrl: "https://images.metahub.space/poster/small/tt2442560/img",
    trailerYoutubeId: "oVzVdvGIC7U",
    videoUrl: "",
    duration: "6 Saisons",
    durationSeconds: 3400,
    releaseYear: 2013,
    matchPercentage: 96,
    ageRating: "18+",
    quality: "4K UHD",
    type: "series",
    genres: ["Crime", "Drama"],
    cast: ["Cillian Murphy", "Paul Anderson", "Helen McCrory", "Tom Hardy"],
    director: "Steven Knight",
    isTrending: true,
    isTop10: true,
    top10Rank: 5,
    episodes: [
      { id: "tt2442560:1:1", season: 1, episode: 1, title: "Épisode 1", overview: "À Birmingham en 1919, Thomas Shelby dirige le redouté gang des Peaky Blinders.", thumbnail: "https://episodes.metahub.space/tt2442560/1/1/w780.jpg" },
      { id: "tt2442560:1:2", season: 1, episode: 2, title: "Épisode 2", overview: "Thomas défie la famille Lee tandis que l'inspecteur Campbell intensifie ses recherches d'armes.", thumbnail: "https://episodes.metahub.space/tt2442560/1/2/w780.jpg" },
    ],
    subtitles: [
      { id: "sub_ar", label: "العربية (Arabic)", language: "ar", src: "/subtitles/sample_ar.vtt", isDefault: true },
      { id: "sub_fr", label: "Français", language: "fr", src: "/subtitles/sample_fr.vtt" },
      { id: "sub_en", label: "English [CC]", language: "en", src: "/subtitles/sample_en.vtt" },
    ],
    audioTracks: [{ id: "aud_en", label: "English", language: "en", isDefault: true }],
  },
  {
    id: "tt12637874",
    imdbId: "tt12637874",
    title: "Fallout",
    originalTitle: "Fallout",
    description: "In a future, post-apocalyptic Los Angeles brought about by nuclear decimation, citizens must live in underground bunkers to protect themselves from radiation, mutants and bandits.",
    backdropUrl: "https://images.metahub.space/background/medium/tt12637874/img",
    posterUrl: "https://images.metahub.space/poster/small/tt12637874/img",
    trailerYoutubeId: "V-mugKDQDlg",
    videoUrl: "",
    duration: "1 Saison",
    durationSeconds: 3600,
    releaseYear: 2024,
    matchPercentage: 97,
    ageRating: "18+",
    quality: "4K UHD",
    type: "series",
    genres: ["Action", "Adventure", "Drama", "Sci-Fi"],
    cast: ["Ella Purnell", "Aaron Moten", "Walton Goggins"],
    director: "Jonathan Nolan",
    isTrending: true,
    isTop10: true,
    top10Rank: 6,
    episodes: [
      { id: "tt12637874:1:1", season: 1, episode: 1, title: "Épisode 1 : La Fin", overview: "Lucy quitte l'abri 33 pour s'aventurer dans un monde de surface désolé et sans pitié.", thumbnail: "https://episodes.metahub.space/tt12637874/1/1/w780.jpg" },
      { id: "tt12637874:1:2", season: 1, episode: 2, title: "Épisode 2 : La Cible", overview: "Lucy rencontre un chercheur en fuite et le redoutable Ghoul.", thumbnail: "https://episodes.metahub.space/tt12637874/1/2/w780.jpg" },
    ],
    subtitles: [
      { id: "sub_ar", label: "العربية (Arabic)", language: "ar", src: "/subtitles/sample_ar.vtt", isDefault: true },
      { id: "sub_fr", label: "Français", language: "fr", src: "/subtitles/sample_fr.vtt" },
      { id: "sub_en", label: "English [CC]", language: "en", src: "/subtitles/sample_en.vtt" },
    ],
    audioTracks: [{ id: "aud_en", label: "English [Atmos]", language: "en", isDefault: true }],
  },
];

